package org.motechproject.care.reporting.domain.dimension;

// Generated May 16, 2013 2:49:27 PM by Hibernate Tools 3.4.0.CR1

import org.motechproject.care.reporting.domain.measure.*;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Flw generated by hbm2java
 */
@Entity
@Table(name = "flw")
public class Flw implements java.io.Serializable {

	private int id;
	private String name;
	private Set<MiForm> miForms = new HashSet<MiForm>(0);
	private Set<ReferMotherForm> referMotherForms = new HashSet<ReferMotherForm>(
			0);
	private Set<UiMotherForm> uiMotherForms = new HashSet<UiMotherForm>(0);
	private Set<CloseMotherForm> closeMotherForms = new HashSet<CloseMotherForm>(
			0);
	private Set<FlwGroupMap> flwGroupMaps = new HashSet<FlwGroupMap>(0);
	private Set<CfChildForm> cfChildForms = new HashSet<CfChildForm>(0);
	private Set<DeathMotherForm> deathMotherForms = new HashSet<DeathMotherForm>(
			0);
	private Set<EbfChildForm> ebfChildForms = new HashSet<EbfChildForm>(0);
	private Set<ReferChildForm> referChildForms = new HashSet<ReferChildForm>(0);
	private Set<CfMotherForm> cfMotherForms = new HashSet<CfMotherForm>(0);
	private Set<BpForm> bpForms = new HashSet<BpForm>(0);
	private Set<UiChildForm> uiChildForms = new HashSet<UiChildForm>(0);
	private Set<RegistrationMotherForm> registrationMotherForms = new HashSet<RegistrationMotherForm>(
			0);
	private Set<PncMotherForm> pncMotherForms = new HashSet<PncMotherForm>(0);
	private Set<AbortForm> abortForms = new HashSet<AbortForm>(0);
	private Set<NewForm> newForms = new HashSet<NewForm>(0);
	private Set<EbfMotherForm> ebfMotherForms = new HashSet<EbfMotherForm>(0);
	private Set<DeathChildForm> deathChildForms = new HashSet<DeathChildForm>(0);
	private Set<CloseChildForm> closeChildForms = new HashSet<CloseChildForm>(0);
	private Set<RegistrationChildForm> registrationChildForms = new HashSet<RegistrationChildForm>(
			0);
	private Set<PncChildForm> pncChildForms = new HashSet<PncChildForm>(0);
	private Set<MoForm> moForms = new HashSet<MoForm>(0);

	public Flw() {
	}

	public Flw(int id) {
		this.id = id;
	}

	public Flw(int id, String name, Set<MiForm> miForms,
			Set<ReferMotherForm> referMotherForms,
			Set<UiMotherForm> uiMotherForms,
			Set<CloseMotherForm> closeMotherForms,
			Set<FlwGroupMap> flwGroupMaps, Set<CfChildForm> cfChildForms,
			Set<DeathMotherForm> deathMotherForms,
			Set<EbfChildForm> ebfChildForms,
			Set<ReferChildForm> referChildForms,
			Set<CfMotherForm> cfMotherForms, Set<BpForm> bpForms,
			Set<UiChildForm> uiChildForms,
			Set<RegistrationMotherForm> registrationMotherForms,
			Set<PncMotherForm> pncMotherForms, Set<AbortForm> abortForms,
			Set<NewForm> newForms, Set<EbfMotherForm> ebfMotherForms,
			Set<DeathChildForm> deathChildForms,
			Set<CloseChildForm> closeChildForms,
			Set<RegistrationChildForm> registrationChildForms,
			Set<PncChildForm> pncChildForms, Set<MoForm> moForms) {
		this.id = id;
		this.name = name;
		this.miForms = miForms;
		this.referMotherForms = referMotherForms;
		this.uiMotherForms = uiMotherForms;
		this.closeMotherForms = closeMotherForms;
		this.flwGroupMaps = flwGroupMaps;
		this.cfChildForms = cfChildForms;
		this.deathMotherForms = deathMotherForms;
		this.ebfChildForms = ebfChildForms;
		this.referChildForms = referChildForms;
		this.cfMotherForms = cfMotherForms;
		this.bpForms = bpForms;
		this.uiChildForms = uiChildForms;
		this.registrationMotherForms = registrationMotherForms;
		this.pncMotherForms = pncMotherForms;
		this.abortForms = abortForms;
		this.newForms = newForms;
		this.ebfMotherForms = ebfMotherForms;
		this.deathChildForms = deathChildForms;
		this.closeChildForms = closeChildForms;
		this.registrationChildForms = registrationChildForms;
		this.pncChildForms = pncChildForms;
		this.moForms = moForms;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flw")
	public Set<MiForm> getMiForms() {
		return this.miForms;
	}

	public void setMiForms(Set<MiForm> miForms) {
		this.miForms = miForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flw")
	public Set<ReferMotherForm> getReferMotherForms() {
		return this.referMotherForms;
	}

	public void setReferMotherForms(Set<ReferMotherForm> referMotherForms) {
		this.referMotherForms = referMotherForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flw")
	public Set<UiMotherForm> getUiMotherForms() {
		return this.uiMotherForms;
	}

	public void setUiMotherForms(Set<UiMotherForm> uiMotherForms) {
		this.uiMotherForms = uiMotherForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flw")
	public Set<CloseMotherForm> getCloseMotherForms() {
		return this.closeMotherForms;
	}

	public void setCloseMotherForms(Set<CloseMotherForm> closeMotherForms) {
		this.closeMotherForms = closeMotherForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flw")
	public Set<FlwGroupMap> getFlwGroupMaps() {
		return this.flwGroupMaps;
	}

	public void setFlwGroupMaps(Set<FlwGroupMap> flwGroupMaps) {
		this.flwGroupMaps = flwGroupMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flw")
	public Set<CfChildForm> getCfChildForms() {
		return this.cfChildForms;
	}

	public void setCfChildForms(Set<CfChildForm> cfChildForms) {
		this.cfChildForms = cfChildForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flw")
	public Set<DeathMotherForm> getDeathMotherForms() {
		return this.deathMotherForms;
	}

	public void setDeathMotherForms(Set<DeathMotherForm> deathMotherForms) {
		this.deathMotherForms = deathMotherForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flw")
	public Set<EbfChildForm> getEbfChildForms() {
		return this.ebfChildForms;
	}

	public void setEbfChildForms(Set<EbfChildForm> ebfChildForms) {
		this.ebfChildForms = ebfChildForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flw")
	public Set<ReferChildForm> getReferChildForms() {
		return this.referChildForms;
	}

	public void setReferChildForms(Set<ReferChildForm> referChildForms) {
		this.referChildForms = referChildForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flw")
	public Set<CfMotherForm> getCfMotherForms() {
		return this.cfMotherForms;
	}

	public void setCfMotherForms(Set<CfMotherForm> cfMotherForms) {
		this.cfMotherForms = cfMotherForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flw")
	public Set<BpForm> getBpForms() {
		return this.bpForms;
	}

	public void setBpForms(Set<BpForm> bpForms) {
		this.bpForms = bpForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flw")
	public Set<UiChildForm> getUiChildForms() {
		return this.uiChildForms;
	}

	public void setUiChildForms(Set<UiChildForm> uiChildForms) {
		this.uiChildForms = uiChildForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flw")
	public Set<RegistrationMotherForm> getRegistrationMotherForms() {
		return this.registrationMotherForms;
	}

	public void setRegistrationMotherForms(
			Set<RegistrationMotherForm> registrationMotherForms) {
		this.registrationMotherForms = registrationMotherForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flw")
	public Set<PncMotherForm> getPncMotherForms() {
		return this.pncMotherForms;
	}

	public void setPncMotherForms(Set<PncMotherForm> pncMotherForms) {
		this.pncMotherForms = pncMotherForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flw")
	public Set<AbortForm> getAbortForms() {
		return this.abortForms;
	}

	public void setAbortForms(Set<AbortForm> abortForms) {
		this.abortForms = abortForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flw")
	public Set<NewForm> getNewForms() {
		return this.newForms;
	}

	public void setNewForms(Set<NewForm> newForms) {
		this.newForms = newForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flw")
	public Set<EbfMotherForm> getEbfMotherForms() {
		return this.ebfMotherForms;
	}

	public void setEbfMotherForms(Set<EbfMotherForm> ebfMotherForms) {
		this.ebfMotherForms = ebfMotherForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flw")
	public Set<DeathChildForm> getDeathChildForms() {
		return this.deathChildForms;
	}

	public void setDeathChildForms(Set<DeathChildForm> deathChildForms) {
		this.deathChildForms = deathChildForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flw")
	public Set<CloseChildForm> getCloseChildForms() {
		return this.closeChildForms;
	}

	public void setCloseChildForms(Set<CloseChildForm> closeChildForms) {
		this.closeChildForms = closeChildForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flw")
	public Set<RegistrationChildForm> getRegistrationChildForms() {
		return this.registrationChildForms;
	}

	public void setRegistrationChildForms(
			Set<RegistrationChildForm> registrationChildForms) {
		this.registrationChildForms = registrationChildForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flw")
	public Set<PncChildForm> getPncChildForms() {
		return this.pncChildForms;
	}

	public void setPncChildForms(Set<PncChildForm> pncChildForms) {
		this.pncChildForms = pncChildForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flw")
	public Set<MoForm> getMoForms() {
		return this.moForms;
	}

	public void setMoForms(Set<MoForm> moForms) {
		this.moForms = moForms;
	}

}
