package org.motechproject.care.reporting.domain.dimension;

// Generated May 16, 2013 2:49:27 PM by Hibernate Tools 3.4.0.CR1

import org.motechproject.care.reporting.domain.measure.NewForm;
import org.motechproject.care.reporting.domain.measure.RegistrationChildForm;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * FlwGroup generated by hbm2java
 */
@Entity
@Table(name = "flw_group")
public class FlwGroup implements java.io.Serializable {

	private int id;
	private String name;
	private Set<FlwGroupMap> flwGroupMaps = new HashSet<FlwGroupMap>(0);
	private Set<ChildCase> childCases = new HashSet<ChildCase>(0);
	private Set<RegistrationChildForm> registrationChildForms = new HashSet<RegistrationChildForm>(
			0);
	private Set<MotherCase> motherCases = new HashSet<MotherCase>(0);
	private Set<NewForm> newForms = new HashSet<NewForm>(0);

	public FlwGroup() {
	}

	public FlwGroup(int id) {
		this.id = id;
	}

	public FlwGroup(int id, String name, Set<FlwGroupMap> flwGroupMaps,
			Set<ChildCase> childCases,
			Set<RegistrationChildForm> registrationChildForms,
			Set<MotherCase> motherCases, Set<NewForm> newForms) {
		this.id = id;
		this.name = name;
		this.flwGroupMaps = flwGroupMaps;
		this.childCases = childCases;
		this.registrationChildForms = registrationChildForms;
		this.motherCases = motherCases;
		this.newForms = newForms;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flwGroup")
	public Set<FlwGroupMap> getFlwGroupMaps() {
		return this.flwGroupMaps;
	}

	public void setFlwGroupMaps(Set<FlwGroupMap> flwGroupMaps) {
		this.flwGroupMaps = flwGroupMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flwGroup")
	public Set<ChildCase> getChildCases() {
		return this.childCases;
	}

	public void setChildCases(Set<ChildCase> childCases) {
		this.childCases = childCases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flwGroup")
	public Set<RegistrationChildForm> getRegistrationChildForms() {
		return this.registrationChildForms;
	}

	public void setRegistrationChildForms(
			Set<RegistrationChildForm> registrationChildForms) {
		this.registrationChildForms = registrationChildForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flwGroup")
	public Set<MotherCase> getMotherCases() {
		return this.motherCases;
	}

	public void setMotherCases(Set<MotherCase> motherCases) {
		this.motherCases = motherCases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flwGroup")
	public Set<NewForm> getNewForms() {
		return this.newForms;
	}

	public void setNewForms(Set<NewForm> newForms) {
		this.newForms = newForms;
	}

}
