package org.motechproject.care.reporting.domain.dimension;

// Generated May 16, 2013 2:49:27 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FlwGroupMapId generated by hbm2java
 */
@Embeddable
public class FlwGroupMapId implements java.io.Serializable {

	private Integer flwId;
	private Integer groupId;

	public FlwGroupMapId() {
	}

	public FlwGroupMapId(Integer flwId, Integer groupId) {
		this.flwId = flwId;
		this.groupId = groupId;
	}

	@Column(name = "flw_id")
	public Integer getFlwId() {
		return this.flwId;
	}

	public void setFlwId(Integer flwId) {
		this.flwId = flwId;
	}

	@Column(name = "group_id")
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FlwGroupMapId))
			return false;
		FlwGroupMapId castOther = (FlwGroupMapId) other;

		return ((this.getFlwId() == castOther.getFlwId()) || (this.getFlwId() != null
				&& castOther.getFlwId() != null && this.getFlwId().equals(
				castOther.getFlwId())))
				&& ((this.getGroupId() == castOther.getGroupId()) || (this
						.getGroupId() != null && castOther.getGroupId() != null && this
						.getGroupId().equals(castOther.getGroupId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFlwId() == null ? 0 : this.getFlwId().hashCode());
		result = 37 * result
				+ (getGroupId() == null ? 0 : this.getGroupId().hashCode());
		return result;
	}

}
