<case case_id="$caseId$" date_modified="2013-06-17" user_id="$userId$" xmlns:n1="http://commcarehq.org/case/transaction/v2">
    <create>
        <case_type>cc_bihar_pregnancy</case_type>
        <owner_id>$ownerId$</owner_id>
        <case_name>&#2352;&#2306;&#2332;&#2344; &#2342;&#2375;&#2357;&#2368;</case_name>
    </create>
    <update>
        <last_visit_type>new</last_visit_type>
        <date_last_visit>2012-12-06</date_last_visit>
        <date_next_reg>2012-12-06</date_next_reg>
        <mother_alive>yes</mother_alive>
        <mother_name>&#2352;&#2306;&#2332;&#2344; &#2342;&#2375;&#2357;&#2368;</mother_name>
        <husband_name>&#2346;&#2381;&#2352;&#2350;&#2379;&#2342; &#2350;&#2369;&#2326;&#2367;&#2351;&#2366;</husband_name>
        <hh_number>44</hh_number>
        <family_number>2</family_number>
        <status>active</status>
        <mobile_number>8969812922</mobile_number>
        <mother_dob>1989-06-01</mother_dob>
        <num_boys>1</num_boys>
        <add />
        <last_visit_type>reg</last_visit_type>
        <date_last_visit>2012-12-06</date_last_visit>
        <family_planning_type />
        <edd>2013-03-16</edd>
        <age>23</age>
        <lmp>2012-06-09</lmp>
        <birth_place>public</birth_place>
        <how_many_children />
        <eats_meat>yes</eats_meat>
        <enrolled_in_kilkari>no</enrolled_in_kilkari>
        <interest_in_kilkari>no</interest_in_kilkari>
        <date_next_bp>2012-12-06</date_next_bp>
    </update>
</case>