<?xml version='1.0' ?>
<data uiVersion="1" version="1" name="MTP Abort" xmlns:cc="http://commcarehq.org/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/mtp_abort">
    <n0:meta xmlns:n0="http://openrosa.org/jr/xforms">
        <n0:deviceID>N2QC8PDLLYJALRQ2VYO3HU891</n0:deviceID>
        <n0:timeStart>2012-11-06T14:49:55.087+05:30</n0:timeStart>
        <n0:timeEnd>2012-11-06T15:01:21.184+05:30</n0:timeEnd>
        <n0:username>8969820824</n0:username>
        <n0:userID>$userId$</n0:userID>
        <n0:instanceID>$instanceId$</n0:instanceID>
        <cc:appVersion>v2.0.0alpha (990ba3-e6e3c5-unvers-2.1.0-Nokia/S40-native-input) #48 b:2012-Jul-26 r:2012-Jul-28</cc:appVersion>
    </n0:meta>
    <n1:case case_id="$caseId$" date_modified="2012-11-06T15:01:21.184+05:30" user_id="$userId$" xmlns:n1="http://commcarehq.org/case/transaction/v2">
        <n1:update>
            <n1:birth_status>still_birth</n1:birth_status>
        </n1:update>
        <n1:close />
    </n1:case>
    <abortion_type>spontaneous</abortion_type>
    <date_aborted>2012-10-22</date_aborted>
    <success>OK</success>
</data>