<?xml version='1.0' ?>
<data uiVersion="1" version="658" name="Mother THR" xmlns:jrm="http://dev.commcarehq.org/jr/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/aww_mother_thr">
    <collect_ration>yes</collect_ration>
    <distribute_ration>yes</distribute_ration>
    <days_ration_given>25</days_ration_given>
    <success>OK</success>
    <mother_rations>pregnant</mother_rations>
    <mother_name>Nitu devi</mother_name>
    <n0:case case_id="$caseId$" date_modified="2014-01-18T15:45:15.073+05:30" user_id="$userId$" xmlns:n0="http://commcarehq.org/case/transaction/v2">
        <n0:update />
    </n0:case>
    <n1:meta xmlns:n1="http://openrosa.org/jr/xforms">
        <n1:deviceID>I28GFS69WUIYJUZ7Z3K7CLJKD</n1:deviceID>
        <n1:timeStart>2014-01-18T15:44:57.558+05:30</n1:timeStart>
        <n1:timeEnd>2014-01-18T15:45:15.073+05:30</n1:timeEnd>
        <n1:username>9973182902a</n1:username>
        <n1:userID>$userId$</n1:userID>
        <n1:instanceID>$instanceId$</n1:instanceID>
        <n2:appVersion xmlns:n2="http://commcarehq.org/xforms">v2.9.0 (6b1e95-e699cd-unvers-2.1.0-Nokia/S40-native-input) build 23681 App #661 b:2013-Sep-30 r:2013-Nov-15</n2:appVersion>
    </n1:meta>
</data>