<?xml version='1.0' ?>
<data uiVersion="1" version="658" name="Child Takehome Ration" xmlns:jrm="http://dev.commcarehq.org/jr/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/aww_child_thr">
    <collect_ration>yes</collect_ration>
    <child_distribute_ration>yes</child_distribute_ration>
    <child_amount_given>normal</child_amount_given>
    <success>OK</success>
    <child_name>testChildName</child_name>
    <mother_name>testMotherName</mother_name>
    <n0:case case_id="$child1caseId$" date_modified="2014-01-18T15:42:08.945+05:30" user_id="$userId$" xmlns:n0="http://commcarehq.org/case/transaction/v2">
        <n0:update />
    </n0:case>
    <n1:meta xmlns:n1="http://openrosa.org/jr/xforms">
        <n1:deviceID>XMPYRBSACQRQGIVG2K90IU3H8</n1:deviceID>
        <n1:timeStart>2014-01-18T15:41:18.975+05:30</n1:timeStart>
        <n1:timeEnd>2014-01-18T15:42:08.945+05:30</n1:timeEnd>
        <n1:username>9973183017a</n1:username>
        <n1:userID>$userId$</n1:userID>
        <n1:instanceID>$instanceId$</n1:instanceID>
        <n2:appVersion xmlns:n2="http://commcarehq.org/xforms">v2.9.0 (6b1e95-e699cd-unvers-2.1.0-Nokia/S40-native-input) build 23681 App #661 b:2013-Sep-30 r:2013-Nov-15</n2:appVersion>
    </n1:meta>
</data>