<?xml version='1.0' ?>
<data uiVersion="1" version="658" name="&#2348;&#2330;&#2381;&#2330;&#2366; &#2325;&#2366; &#2344;&#2366;&#2350; &#2348;&#2342;&#2354;&#2375;&#2306;" xmlns:jrm="http://dev.commcarehq.org/jr/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/aww_child_edit">
    <update_child_name>yes</update_child_name>
    <new_child_name>TestName</new_child_name>
    <update_child_dob>no</update_child_dob>
    <success>OK</success>
    <parents>
        <mother_id>
            <n0:case case_id="$caseId$" date_modified="2014-01-18T12:35:15.842+05:30" user_id="$userId$" xmlns:n0="http://commcarehq.org/case/transaction/v2">
                <n0:update />
            </n0:case>
        </mother_id>
    </parents>
    <n1:case case_id="$child1caseId$" date_modified="2014-01-18T12:35:15.842+05:30" user_id="$userId$" xmlns:n1="http://commcarehq.org/case/transaction/v2">
        <n1:update>
            <n1:case_name />
        </n1:update>
    </n1:case>
    <n2:meta xmlns:n2="http://openrosa.org/jr/xforms">
        <n2:deviceID>XMPYRBSACQRQGIVG2K90IU3H8</n2:deviceID>
        <n2:timeStart>2014-01-18T12:35:08.196+05:30</n2:timeStart>
        <n2:timeEnd>2014-01-18T12:35:15.842+05:30</n2:timeEnd>
        <n2:username>9973183017a</n2:username>
        <n2:userID>$userId$</n2:userID>
        <n2:instanceID>$instanceId$</n2:instanceID>
        <n3:appVersion xmlns:n3="http://commcarehq.org/xforms">v2.9.0 (6b1e95-e699cd-unvers-2.1.0-Nokia/S40-native-input) build 23681 App #661 b:2013-Sep-30 r:2013-Nov-15</n3:appVersion>
    </n2:meta>
</data>