<?xml version='1.0' ?>
<data uiVersion="1" version="658" name="&#2357;&#2371;&#2342;&#2381;&#2343;&#2367; &#2344;&#2367;&#2327;&#2352;&#2366;&#2344;&#2368;" xmlns:jrm="http://dev.commcarehq.org/jr/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/aww_growth_monitoring_2">
    <current_growth>growth_normal</current_growth>
    <current_weight_date>2014-01-19</current_weight_date>
    <last_weight_date />
    <current_weight>2.7</current_weight>
    <last_weight>1.8</last_weight>
    <take_weight>yes</take_weight>
    <child_weight>2.7</child_weight>
    <show_grade>OK</show_grade>
    <success>OK</success>
    <calc_grade>-2</calc_grade>
    <calc_growth>growth_normal</calc_growth>
    <child_gender>1</child_gender>
    <child_age>0</child_age>
    <dob>2014-01-10</dob>
    <gender>female</gender>
    <change_from_normal>no</change_from_normal>
    <change_from_muw>no</change_from_muw>
    <change_from_suw>no</change_from_suw>
    <age_last_weight>5</age_last_weight>
    <n0:case case_id="$child1caseId$" date_modified="2014-01-19T03:14:23.594Z" user_id="$userId$" xmlns:n0="http://commcarehq.org/case/transaction/v2">
        <n0:update>
            <n0:age_current_weight>0</n0:age_current_weight>
            <n0:age_last_weight />
            <n0:current_growth>growth_normal</n0:current_growth>
            <n0:current_weight>2.7</n0:current_weight>
            <n0:current_weight_date>2014-01-19</n0:current_weight_date>
            <n0:last_growth_1 />
            <n0:last_growth_2 />
            <n0:last_growth_3 />
            <n0:last_weight />
            <n0:last_weight_date />
        </n0:update>
    </n0:case>
    <n1:meta xmlns:n1="http://openrosa.org/jr/xforms">
        <n1:deviceID>72U3S2YLYOFDASQHTHXVTHBXM</n1:deviceID>
        <n1:timeStart>2014-01-19T03:13:57.981Z</n1:timeStart>
        <n1:timeEnd>2014-01-19T03:14:23.594Z</n1:timeEnd>
        <n1:username>9973182735a</n1:username>
        <n1:userID>$userId$</n1:userID>
        <n1:instanceID>$instanceId$</n1:instanceID>
        <n2:appVersion xmlns:n2="http://commcarehq.org/xforms">v2.9.0 (6b1e95-e699cd-unvers-2.1.0-Nokia/S40-native-input) build 23681 App #661 b:2013-Sep-30 r:2013-Nov-15</n2:appVersion>
    </n1:meta>
</data>