<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://bihar.commcarehq.org/pregnancy/aww_preschool_activities" xmlns:jrm="http://dev.commcarehq.org/jr/xforms" uiVersion="1" version="658" name="Preschool Activities Form">
   <menu>khichri other</menu>
   <activity>prayer_hygiene conversation cognitive physical_outdoor packup</activity>
   <child>
      <child_attend>yes</child_attend>
      <breakfast>normal</breakfast>
      <participated>participated</participated>
      <lunch>normal</lunch>
      <caseid>0f3da26a-c388-4550-9552-1901b023148a</caseid>
   </child>
   <success>OK</success>
   <num_children>1</num_children>
   <child_ids>0f3da26a-c388-4550-9552-1901b023148a</child_ids>
   <n0:meta xmlns:n0="http://openrosa.org/jr/xforms">
      <n0:deviceID>AKQWLY37YOIHN896W23UWVNI4</n0:deviceID>
      <n0:timeStart>2014-01-18T12:35:08.196+05:30</n0:timeStart>
      <n0:timeEnd>2014-01-18T12:35:08.196+05:30</n0:timeEnd>
      <n0:username>8969816409a</n0:username>
      <n0:userID>$userId$</n0:userID>
      <n0:instanceID>$instanceId$</n0:instanceID>
      <n1:appVersion xmlns:n1="http://commcarehq.org/xforms">v2.9.0 (6b1e95-e699cd-unvers-2.1.0-Nokia/S40-native-input) build 23681 App #661 b:2013-Sep-30 r:2013-Nov-15</n1:appVersion>
   </n0:meta>
</data>
