<?xml version='1.0' ?>
<data uiVersion="1" version="618" name="&#2335;&#2368;&#2325;&#2366;&#2325;&#2352;&#2339; &#2309;&#2346;&#2337;&#2375;&#2335;" xmlns:jrm="http://dev.commcarehq.org/jr/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/aww_update_vaccinations">
    <details_available>yes</details_available>
    <add_vaccinations>no</add_vaccinations>
    <up_to_date_six_weeks>no</up_to_date_six_weeks>
    <up_to_date_ten_weeks>no</up_to_date_ten_weeks>
    <up_to_date_14_weeks>no</up_to_date_14_weeks>
    <up_to_date_one_year>no</up_to_date_one_year>
    <up_to_date_two_year>no</up_to_date_two_year>
    <success>OK</success>
    <immuns_up_to_date>no</immuns_up_to_date>
    <child_name>testChildName</child_name>
    <dob>2013-01-28</dob>
    <n0:case case_id="$child1caseId$"  date_modified="2014-01-17T12:40:31.144+05:30" user_id="$userId$" xmlns:n0="http://commcarehq.org/case/transaction/v2">
        <n0:update />
    </n0:case>
    <n1:meta xmlns:n1="http://openrosa.org/jr/xforms">
        <n1:deviceID>54SVO8CC6EDAH1FV2WLK0DWNZ</n1:deviceID>
        <n1:timeStart>2014-01-17T12:27:40.273+05:30</n1:timeStart>
        <n1:timeEnd>2014-01-17T12:40:31.144+05:30</n1:timeEnd>
        <n1:username>8969816164a</n1:username>
        <n1:userID>$userId$</n1:userID>
        <n1:instanceID>$instanceId$</n1:instanceID>
        <n2:appVersion xmlns:n2="http://commcarehq.org/xforms">v2.9.0 (6b1e95-e699cd-unvers-2.1.0-Nokia/S40-native-input) build 23681 App #661 b:2013-Sep-30 r:2013-Nov-15</n2:appVersion>
    </n1:meta>
</data>