<?xml version='1.0' ?>
<data uiVersion="1" version="658" name="Register Child" xmlns:jrm="http://dev.commcarehq.org/jr/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/aww_reg_child">
    <child_alive>yes</child_alive>
    <gender>female</gender>
    <dob>2008-11-21</dob>
    <mother_name>testMotherName</mother_name>
    <husband_name>testFatherName</husband_name>
    <hh_number>5</hh_number>
    <ward_number>7</ward_number>
    <family_number>9</family_number>
    <mobile_number>9622318490</mobile_number>
    <mobile_number_whose>mobile_parents</mobile_number_whose>
    <eats_meat>yes</eats_meat>
    <child_name>testChildName</child_name>
    <dob_known>no</dob_known>
    <age_est_months>2</age_est_months>
    <age_est_years>5</age_est_years>
    <father_name>testFatherName</father_name>
    <update_mcts_id>no</update_mcts_id>
    <update_aadhar_number>no</update_aadhar_number>
    <caste>other</caste>
    <resident>resident</resident>
    <success>OK</success>
    <owner_id_calc>83d5ef14d0ca819665bff318576b55e0</owner_id_calc>
    <subcase_0>
        <n0:case case_id="$child1caseId$" date_modified="2014-01-20T17:01:26.961+05:30" user_id="$userId$" xmlns:n0="http://commcarehq.org/case/transaction/v2">
            <n0:create>
                <n0:case_name>testChildCaseName</n0:case_name>
                <n0:owner_id>-</n0:owner_id>
                <n0:case_type>cc_bihar_newborn</n0:case_type>
            </n0:create>
            <n0:update>
                <n0:child_alive>yes</n0:child_alive>
                <n0:dob>2008-11-21</n0:dob>
                <n0:gender>female</n0:gender>
                <n0:owner_id>83d5ef14d0ca819665bff318576b55e0</n0:owner_id>
            </n0:update>
            <n0:index>
                <n0:mother_id case_type="cc_bihar_pregnancy">37ee6ed7-d649-45ab-b2ff-fbb880a18759</n0:mother_id>
            </n0:index>
        </n0:case>
    </subcase_0>
    <n1:case case_id="$caseId$" date_modified="2014-01-20T17:01:26.961+05:30" user_id="$userId$" xmlns:n1="http://commcarehq.org/case/transaction/v2">
        <n1:create>
            <n1:case_name>testMotherCaseName</n1:case_name>
            <n1:owner_id>-</n1:owner_id>
            <n1:case_type>cc_bihar_pregnancy</n1:case_type>
        </n1:create>
        <n1:update>
            <n1:add>2008-11-21</n1:add>
            <n1:eats_meat>yes</n1:eats_meat>
            <n1:family_number>9</n1:family_number>
            <n1:hh_number>5</n1:hh_number>
            <n1:husband_name>&#2346;&#2346;&#2381;&#2346;&#2369; &#2327;&#2369;&#2346;&#2381;&#2340;&#2366;</n1:husband_name>
            <n1:mobile_number>9622318490</n1:mobile_number>
            <n1:mobile_number_whose>mobile_parents</n1:mobile_number_whose>
            <n1:mother_name>&#2310;&#2358;&#2366; &#2342;&#2375;&#2357;&#2368;</n1:mother_name>
            <n1:owner_id>83d5ef14d0ca819665bff318576b55e0</n1:owner_id>
            <n1:ward_number>7</n1:ward_number>
        </n1:update>
    </n1:case>
    <n2:meta xmlns:n2="http://openrosa.org/jr/xforms">
        <n2:deviceID>Y6MRHT4CS0CRGBDKUL77BAPHT</n2:deviceID>
        <n2:timeStart>2014-01-20T16:53:32.329+05:30</n2:timeStart>
        <n2:timeEnd>2014-01-20T17:01:26.961+05:30</n2:timeEnd>
        <n2:username>8969821093a</n2:username>
        <n2:userID>$userId$</n2:userID>
        <n2:instanceID>$instanceId$</n2:instanceID>
        <n3:appVersion xmlns:n3="http://commcarehq.org/xforms">v2.9.0 (6b1e95-e699cd-unvers-2.1.0-Nokia/S40-native-input) build 23681 App #661 b:2013-Sep-30 r:2013-Nov-15</n3:appVersion>
    </n2:meta>
</data>