<?xml version='1.0' ?>
<data uiVersion="1" version="1" name="Birth Preparedness" xmlns:cc="http://commcarehq.org/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/bp">
    <n0:meta xmlns:n0="http://openrosa.org/jr/xforms">
        <n0:deviceID>4GHEMY8AM4I0Y4W8Q6401K433</n0:deviceID>
        <n0:timeStart>2012-09-08T12:24:28.920+05:30</n0:timeStart>
        <n0:timeEnd>2012-09-08T12:30:15.907+05:30</n0:timeEnd>
        <n0:username>8969818460</n0:username>
        <n0:userID>$userId$</n0:userID>
        <n0:instanceID>$instanceId$</n0:instanceID>
        <cc:appVersion>v2.0.0alpha (990ba3-e6e3c5-unvers-2.1.0-Nokia/S40-native-input) #48 b:2012-Jul-26 r:2012-Jul-28</cc:appVersion>
    </n0:meta>
    <n1:case case_id="$caseId$" date_modified="2012-09-08T12:30:15.907+05:30" user_id="$userId$" xmlns:n1="http://commcarehq.org/case/transaction/v2">

        <n1:update>
            <n1:tt_booster_date>2012-07-30</n1:tt_booster_date>
            <n1:anc_2_date>2013-04-12</n1:anc_2_date>
            <n1:anc_1_date>2013-01-10</n1:anc_1_date>

            <n1:anc_4_date>2012-12-12</n1:anc_4_date>
            <n1:anc_3_date>2012-11-08</n1:anc_3_date>

            <n1:ifa_tablets_100>2012-09-08</n1:ifa_tablets_100>
            <n1:ifa_tablets>100</n1:ifa_tablets>
            <n1:institutional>yes</n1:institutional>
            <n1:institutional>yes</n1:institutional>
            <n1:vehicle>yes</n1:vehicle>
            <n1:maternal_emergency>yes</n1:maternal_emergency>
            <n1:couple_interested>undecided</n1:couple_interested>
            <n1:maternal_emergency_number>no</n1:maternal_emergency_number>
            <n1:accompany>yes</n1:accompany>
            <n1:phone_vehicle>yes</n1:phone_vehicle>
            <n1:saving_money>yes</n1:saving_money>
            <n1:delivery_type>institutional</n1:delivery_type>

            <n1:materials>yes</n1:materials>
            <n1:clean_cloth>yes</n1:clean_cloth>


            <n1:date_bp_1>2012-09-08</n1:date_bp_1>
            <n1:date_bp_2>2012-09-08</n1:date_bp_2>
            <n1:date_bp_3>2012-09-08</n1:date_bp_3>


            <n1:tt_2_date>2012-08-16</n1:tt_2_date>
            <n1:tt_1_date>2012-07-09</n1:tt_1_date>

            <n1:date_next_bp>2012-09-16</n1:date_next_bp>
            <n1:last_visit_type>bp</n1:last_visit_type>
            <n1:date_last_visit>2012-09-08</n1:date_last_visit>

            <n1:SBA_phone>yes</n1:SBA_phone>
            <n1:SBA>yes</n1:SBA>

        </n1:update>
    </n1:case>
    <bp_visit_num>1</bp_visit_num>
    <delivery_type>institutional</delivery_type>
    <anc_latest_num>1</anc_latest_num>
    <anc_latest_date>2012-09-08</anc_latest_date>


    <bp2>
        <now_institutional>yes</now_institutional>

        <SBA>yes</SBA>
        <SBA_phone>yes</SBA_phone>
        <materials>yes</materials>
        <clean_cloth>yes</clean_cloth>

        <counsel_institutional>yes</counsel_institutional>
        <counsel_home_delivery>yes</counsel_home_delivery>

        <inform_danger_signs>yes</inform_danger_signs>

        <play_birth_preparedness_vid>yes</play_birth_preparedness_vid>
        <birth_preparedness_vid>OK</birth_preparedness_vid>
        <saving_money>yes</saving_money>
        <vehicle>yes</vehicle>
        <phone_vehicle>yes</phone_vehicle>
        <accompany>yes</accompany>
        <care_of_home>yes</care_of_home>
        <counsel_preparation>yes</counsel_preparation>
        <maternal_danger_signs>yes</maternal_danger_signs>
        <has_danger_signs>no</has_danger_signs>
        <not_yet_maternal_emergency>OK</not_yet_maternal_emergency>
        <danger_institution>yes</danger_institution>
        <danger_number>yes</danger_number>
        <play_cord_care_vid>yes</play_cord_care_vid>
        <cord_care_vid>OK</cord_care_vid>
        <wrapping>yes</wrapping>
        <skin_to_skin>yes</skin_to_skin>
        <immediate_breastfeeding>yes</immediate_breastfeeding>
        <cord_care>yes</cord_care>
    </bp2>

    <bp1>
        <ifa_tablets_issued>100</ifa_tablets_issued>
        <total_ifa>OK</total_ifa>
        <counsel_ifa>yes</counsel_ifa>
        <using_ifa>yes</using_ifa>
        <counsel_tt>yes</counsel_tt>
        <tt_booster>yes</tt_booster>

        <reason_no_ifa>dont_remember</reason_no_ifa>

        <tt_booster_date>2012-07-30</tt_booster_date>

        <received_tt1>yes</received_tt1>
        <tt1_date>2013-01-10</tt1_date>
        <received_tt2>no</received_tt2>


        <resting>yes</resting>
        <eating_extra>yes</eating_extra>


        <anc1_details>yes</anc1_details>
        <anc1>
            <anc1_date>2013-01-10</anc1_date>
            <anc1_facility>public</anc1_facility>
            <anc1_blood_pressure>not_measured</anc1_blood_pressure>
            <anc1_abdominal_exam>performed</anc1_abdominal_exam>
            <anc1_abnormalities>no</anc1_abnormalities>
        </anc1>

        <anc2_details>yes</anc2_details>
        <anc2>
            <anc2_date>2013-04-12</anc2_date>
            <anc2_facility>public</anc2_facility>
            <anc2_blood_pressure>normal</anc2_blood_pressure>
            <anc2_abdominal_exam>performed</anc2_abdominal_exam>
            <anc2_abnormalities>no</anc2_abnormalities>
        </anc2>

        <anc3_details>yes</anc3_details>
        <anc3>
            <anc3_date>2012-11-08</anc3_date>
            <anc3_facility>public</anc3_facility>
            <anc3_blood_pressure>normal</anc3_blood_pressure>
            <anc3_abdominal_exam>performed</anc3_abdominal_exam>
            <anc3_abnormalities>no</anc3_abnormalities>
        </anc3>


        <anc4_details>yes</anc4_details>
        <anc4>
            <anc4_date>2012-12-12</anc4_date>
            <anc4_facility>public</anc4_facility>
            <anc4_blood_pressure>normal</anc4_blood_pressure>
            <anc4_abdominal_exam>performed</anc4_abdominal_exam>
            <anc4_abnormalities>no</anc4_abnormalities>
        </anc4>

        <anc_display>OK</anc_display>


    </bp1>

    <ifa_tablets_total>100</ifa_tablets_total>
    <play_family_planning_vid>no</play_family_planning_vid>
    <conceive>no</conceive>
    <postponing>undecided</postponing>
    <institutional>yes</institutional>


    <family_planning_group>
        <avail_immediate>yes</avail_immediate>
        <counsel_accessible>yes</counsel_accessible>
        <help_decide>OK</help_decide>

        <counsel_accessible>yes</counsel_accessible>
        <counsel_benefits>yes</counsel_benefits>
        <counsel_disqualification>yes</counsel_disqualification>
        <counsel_institution>yes</counsel_institution>
        <counsel_methods>yes</counsel_methods>
        <counsel_nearest>yes</counsel_nearest>
        <counsel_options>yes</counsel_options>
        <counsel_stay>yes</counsel_stay>


        <immediate_appropriate>no</immediate_appropriate>
        <institution_immediate>no</institution_immediate>

        <risk_of_preg>yes</risk_of_preg>
        <stop_children>undecided</stop_children>

        <postpone_conception>yes</postpone_conception>
        <spacing_methods>yes</spacing_methods>

        <risk_of_preg>yes</risk_of_preg>
        <stop_children>yes</stop_children>


    </family_planning_group>
    <success>OK</success>
    <nextvisit>OK</nextvisit>
    <nextvisittype>bp</nextvisittype>
    <del_fup>2013-12-13</del_fup>
</data>