<?xml version='1.0' ?>
<data uiVersion="1" version="1" name="CF" xmlns:cc="http://commcarehq.org/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/cf">
    <n0:meta xmlns:n0="http://openrosa.org/jr/xforms">
        <n0:deviceID>K295IYAKFA3C1X8GQTIRDMUZI</n0:deviceID>
        <n0:timeStart>2013-03-19T12:19:48.311+05:30</n0:timeStart>
        <n0:timeEnd>2013-03-19T12:21:08.576+05:30</n0:timeEnd>
        <n0:username>8969813689</n0:username>
        <n0:userID>$userId$</n0:userID>
        <n0:instanceID>$instanceId$</n0:instanceID>
        <cc:appVersion>v2.0.0alpha (990ba3-e6e3c5-unvers-2.1.0-Nokia/S40-native-input) #48 b:2012-Jul-26 r:2012-Jul-28</cc:appVersion>
    </n0:meta>
    <n1:case case_id="$caseId$" date_modified="2013-03-19T12:21:08.576+05:30" user_id="$userId$" xmlns:n1="http://commcarehq.org/case/transaction/v2">
        <n1:update>
            <n1:last_visit_type>cf</n1:last_visit_type>
            <n1:date_last_visit>2013-03-19</n1:date_last_visit>
            <n1:date_cf_1>2013-03-19</n1:date_cf_1>

            <n1:date_cf_2>2013-03-19</n1:date_cf_2>
            <n1:date_cf_3>2013-03-19</n1:date_cf_3>
            <n1:date_cf_4>2013-03-19</n1:date_cf_4>
            <n1:date_cf_5>2013-03-19</n1:date_cf_5>
            <n1:date_cf_6>2013-03-19</n1:date_cf_6>
            <n1:date_cf_7>2013-03-19</n1:date_cf_7>

            <n1:date_next_cf>2013-04-18</n1:date_next_cf>
        </n1:update>
    </n1:case>
    <cf_visit_num>1</cf_visit_num>
    <play_comp_feeding_vid>yes</play_comp_feeding_vid>
    <comp_feeding_vid>OK</comp_feeding_vid>
    <num_children>1</num_children>
    <children>$child1caseId$</children>
    <child_info>
        <cid>$child1caseId$</cid>
        <index>0</index>
        <n2:case case_id="$child1caseId$" date_modified="2013-05-03T16:05:07.368+05:30" user_id="$userId$" xmlns:n2="http://commcarehq.org/case/transaction/v2">
            <n2:update>
                <n2:bcg_date>2012-01-29</n2:bcg_date>
                <n2:opv_0_date>2012-01-29</n2:opv_0_date>
                <n2:opv_1_date>2012-03-02</n2:opv_1_date>
                <n2:opv_2_date>2012-04-06</n2:opv_2_date>
                <n2:opv_3_date>2012-05-04</n2:opv_3_date>
                <n2:opv_booster_date>2013-05-03</n2:opv_booster_date>
                <n2:dpt_1_date>2012-03-02</n2:dpt_1_date>
                <n2:dpt_2_date>2013-04-06</n2:dpt_2_date>
                <n2:dpt_3_date>2012-05-04</n2:dpt_3_date>
                <n2:dpt_booster_date>2013-05-03</n2:dpt_booster_date>
                <n2:hep_b_0_date>2012-01-29</n2:hep_b_0_date>
                <n2:hep_b_1_date>2012-03-02</n2:hep_b_1_date>
                <n2:hep_b_2_date>2012-04-06</n2:hep_b_2_date>
                <n2:hep_b_3_date>2012-05-04</n2:hep_b_3_date>
                <n2:baby_measles>yes</n2:baby_measles>
                <n2:measles_date>2013-05-03</n2:measles_date>
                <n2:vit_a_1_date>2013-05-03</n2:vit_a_1_date>
                <n2:vit_a_2_date>2013-05-03</n2:vit_a_2_date>
                <n2:vit_a_3_date>2013-05-03</n2:vit_a_3_date>

                <n2:case_name>test</n2:case_name>
                <n2:date_je>2012-03-02</n2:date_je>
                <n2:date_measles_booster>2012-03-02</n2:date_measles_booster>


            </n2:update>
        </n2:case>
        <display_child>OK</display_child>
        <name_update>no</name_update>
        <new_name>test</new_name>
        <eaten_cereal>yes</eaten_cereal>
        <number_good>yes</number_good>
        <amount_good>yes</amount_good>
        <dal>yes</dal>
        <oil_ghee>yes</oil_ghee>
        <milk_curd>yes</milk_curd>
        <egg>yes</egg>
        <fish>yes</fish>
        <meat>yes</meat>
        <recent_fever>no</recent_fever>
        <add_vaccinations>yes</add_vaccinations>
        <baby_bcg>yes</baby_bcg>
        <baby_opv0>yes</baby_opv0>
        <baby_opv1>yes</baby_opv1>
        <baby_opv2>yes</baby_opv2>
        <baby_opv3>yes</baby_opv3>
        <baby_opv_booster>yes</baby_opv_booster>
        <baby_dpt1>yes</baby_dpt1>
        <baby_dpt2>yes</baby_dpt2>
        <baby_dpt3>yes</baby_dpt3>
        <baby_dpt_booster>yes</baby_dpt_booster>
        <baby_hep_b_0>yes</baby_hep_b_0>
        <baby_hep_b_1>yes</baby_hep_b_1>
        <baby_hep_b_2>yes</baby_hep_b_2>
        <baby_hep_b_3>yes</baby_hep_b_3>
        <baby_measles>yes</baby_measles>
        <baby_measles_booster>no</baby_measles_booster>
        <baby_vita1>yes</baby_vita1>
        <baby_vita2>no</baby_vita2>
        <baby_vita3>yes</baby_vita3>
        <more_feeding_less_six>yes</more_feeding_less_six>
        <treated_less_six>yes</treated_less_six>

        <baby_je>no</baby_je>
    </child_info>

    <success>OK</success>
    <nextvisit>OK</nextvisit>

    <case_closing>
        <lastvisit>yes</lastvisit>
        <confirm_close>yes</confirm_close>
        <yes_close_message>OK</yes_close_message>
        <no_close_message>OK</no_close_message>
    </case_closing>


</data>