<?xml version='1.0' ?>
<data uiVersion="1" version="1" name="Close" xmlns:cc="http://commcarehq.org/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/close">
    <n0:meta xmlns:n0="http://openrosa.org/jr/xforms">
        <n0:deviceID>4LL73X5ZSNPDA3JCFKLLJ6BT1</n0:deviceID>
        <n0:timeStart>2013-03-29T11:18:48.012+05:30</n0:timeStart>
        <n0:timeEnd>2013-03-29T11:20:33.216+05:30</n0:timeEnd>
        <n0:username>9973182242</n0:username>
        <n0:userID>$userId$</n0:userID>
        <n0:instanceID>$instanceId$</n0:instanceID>
        <cc:appVersion>v2.0.0alpha (990ba3-e6e3c5-unvers-2.1.0-Nokia/S40-native-input) #48 b:2012-Jul-26 r:2012-Jul-28</cc:appVersion>
    </n0:meta>
    <n1:case case_id="$caseId$" date_modified="2013-03-29T11:20:33.216+05:30" user_id="$userId$" xmlns:n1="http://commcarehq.org/case/transaction/v2">
        <n1:update>
            <n1:mother_alive>none</n1:mother_alive>
        </n1:update>
        <n1:close>None</n1:close>
        <n1:death_village>no</n1:death_village>
        <n1:died>no</n1:died>
        <n1:dupe_reg>no</n1:dupe_reg>
        <n1:moved>yes</n1:moved>
        <n1:migrated>yes</n1:migrated>
        <n1:date_learned>2013-03-29</n1:date_learned>
        <n1:date_left>2013-03-29</n1:date_left>
        <n1:migration_note>yes</n1:migration_note>
        <n1:date_death>2013-03-29</n1:date_death>
        <n1:site_death>ok</n1:site_death>
    </n1:case>
    <close_mother>yes</close_mother>
    <finished_continuum>yes</finished_continuum>
    <died_village />
    <place_village>kottampatti</place_village>
    <status>died</status>
    <confirm_close>yes</confirm_close>
    <yes_closed_message>OK</yes_closed_message>
    <children>$child1caseId$</children>
    <num_children>1</num_children>
    <child_info>
        <cid>$child1caseId$</cid>
        <index>0</index>
        <close_child>yes</close_child>
        <finished_continuum>yes</finished_continuum>
        <confirm_close>yes</confirm_close>
        <yes_closed_message>OK</yes_closed_message>
        <n2:case case_id="$child1caseId$" date_modified="2013-03-29T11:20:33.216+05:30" user_id="$userId$" xmlns:n2="http://commcarehq.org/case/transaction/v2">
            <n2:update />
            <n2:close />
        </n2:case>
    </child_info>

    <success>OK</success>

</data>