<?xml version='1.0' ?>
<data uiVersion="1" version="1" name="Delivery Update" xmlns:cc="http://commcarehq.org/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/del">
    <n0:meta xmlns:n0="http://openrosa.org/jr/xforms">
        <n0:deviceID>3245A73OS62389NXTR7KVVLLS</n0:deviceID>
        <n0:timeStart>2012-11-04T14:42:01.080+05:30</n0:timeStart>
        <n0:timeEnd>2012-11-04T14:51:30.998+05:30</n0:timeEnd>
        <n0:username>8969811424</n0:username>
        <n0:userID>$userId$</n0:userID>
        <n0:instanceID>$instanceId$</n0:instanceID>
        <cc:appVersion>v2.0.0alpha (990ba3-e6e3c5-unvers-2.1.0-Nokia/S40-native-input) #48 b:2012-Jul-26 r:2012-Jul-28</cc:appVersion>
    </n0:meta>
    <n1:case case_id="$caseId$" date_modified="2012-11-04T14:51:30.998+05:30" user_id="$userId$" xmlns:n1="http://commcarehq.org/case/transaction/v2">
        <n1:update>

            <n1:complications>no</n1:complications>
            <n1:date_del_fu>2013-05-15</n1:date_del_fu>
            <n1:date_next_cf>2013-03-07</n1:date_next_cf>
            <n1:date_next_pnc>2012-11-20</n1:date_next_pnc>

            <n1:how_many_children>1</n1:how_many_children>
            <n1:term>pre_term</n1:term>
            <n1:birth_place>public</n1:birth_place>
            <n1:mother_alive>yes</n1:mother_alive>
            <n1:add>2012-10-04</n1:add>
            <n1:family_planning_type>pptl_at_delivery</n1:family_planning_type>
            <n1:last_visit_type>del</n1:last_visit_type>
            <n1:date_last_visit>2012-11-04</n1:date_last_visit>
            <n1:date_next_eb>2012-12-03</n1:date_next_eb>
        </n1:update>
    </n1:case>

    <date_death>2012-11-17</date_death>
    <death_village>yes</death_village>
    <mother_alive>yes</mother_alive>
    <other_district>Madhepura</other_district>
    <other_village>&#2325;&#2369;&#2350;&#2366;&#2352;</other_village>
    <place_death>&#2325;&#2369;&#2350;&#2366;&#2352;</place_death>
    <referral>OK</referral>
    <referral_prompt>OK</referral_prompt>
    <site_death>hospital_death</site_death>

    <has_delivered>yes</has_delivered>
    <notified>2012-10-10</notified>
    <add>2012-10-04</add>
    <safe>yes</safe>
    <where_born>Hospital</where_born>
    <which_hospital>block_phc</which_hospital>
    <in_district>yes</in_district>
    <jsy_money>yes</jsy_money>
    <which_village>this_village</which_village>
    <delivery_nature>vaginal</delivery_nature>
    <how_many_children>1</how_many_children>
    <num_children>1</num_children>
    <child_info>
        <n2:case case_id="$child1caseId$" date_modified="2013-04-25T10:46:45.167Z" user_id="$userId$" xmlns:n2="http://commcarehq.org/case/transaction/v2">
            <n2:create>
                <n2:case_type>cc_bihar_newborn</n2:case_type>
                <n2:owner_id>$groupId$</n2:owner_id>
                <n2:case_name>&#2331;&#2379;&#2335;&#2369; &#2325;&#2369;&#2350;&#2366;&#2352;</n2:case_name>
            </n2:create>
            <n2:update>
                <n2:birth_status>live_birth</n2:birth_status>
                <n2:dob>2013-04-24</n2:dob>
                <n2:gender>male</n2:gender>
                <n2:baby_weight>yes</n2:baby_weight>
                <n2:bcg_date>2013-04-24</n2:bcg_date>
                <n2:opv_0_date>2013-04-24</n2:opv_0_date>
                <n2:hep_b_0_date>2013-04-24</n2:hep_b_0_date>
                <n2:term>full_term</n2:term>
            </n2:update>
            <n2:index>
                <n2:mother_id case_type="cc_bihar_pregnancy">$caseId$</n2:mother_id>
            </n2:index>
        </n2:case>
        <child_have_a_name>yes</child_have_a_name>
        <child_name>&#2331;&#2379;&#2335;&#2369; &#2325;&#2369;&#2350;&#2366;&#2352;</child_name>
        <date_first_weight>2013-04-24</date_first_weight>
        <first_weight>3.0</first_weight>
        <child_cried>yes</child_cried>
        <child_alive>yes</child_alive>
        <skin_care>yes</skin_care>
        <wrapped_dried>yes</wrapped_dried>
        <cord_cut>yes</cord_cut>
        <cord_tied>yes</cord_tied>
        <cord_applied>no</cord_applied>
        <date_time_feed>2013-04-24</date_time_feed>
        <breastfed_hour>yes</breastfed_hour>
        <abnormalities>no</abnormalities>
        <add_vaccinations>yes</add_vaccinations>
        <baby_bcg>yes</baby_bcg>
        <baby_opv0>yes</baby_opv0>
        <baby_hep_b_0>yes</baby_hep_b_0>

        <child_is_breathing>yes</child_is_breathing>

        <child_has_heartbeats>yes</child_has_heartbeats>

        <child_died_village>yes</child_died_village>

        <child_movement>yes</child_movement>
        <child_place_death>&#2325;&#2369;&#2350;&#2366;&#2352;</child_place_death>
        <child_site_death>home</child_site_death>
        <chld_date_death>2013-04-25</chld_date_death>
        <display_child_name>OK</display_child_name>
        <what_applied>gv</what_applied>

    </child_info>

    <complications>yes</complications>
    <fever>no</fever>
    <abd_pain>no</abd_pain>
    <vaginal_discharge>no</vaginal_discharge>
    <pain_urine>no</pain_urine>
    <other_conditions>no</other_conditions>
    <post_postpartum_fp>yes</post_postpartum_fp>
    <PPIUD>no</PPIUD>
    <PPTL>yes</PPTL>
    <ifa_tablets_given>yes</ifa_tablets_given>
    <cast_num_children>1</cast_num_children>
    <success>OK</success>
    <temp>
        <ebf_visit days="14">2012-10-18</ebf_visit>
        <ebf_visit days="28">2012-11-01</ebf_visit>
        <ebf_visit days="60">2012-12-03</ebf_visit>
        <ebf_visit days="90">2013-01-02</ebf_visit>
        <ebf_visit days="120">2013-02-01</ebf_visit>
        <ebf_visit days="150">2013-03-03</ebf_visit>
    </temp>
    <nextvisit>OK</nextvisit>
    <nextvisittype>ebf</nextvisittype>
</data>