<?xml version='1.0' ?>
<data uiVersion="1" version="1" name="EBF" xmlns:cc="http://commcarehq.org/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/ebf">
    <n0:meta xmlns:n0="http://openrosa.org/jr/xforms">
        <n0:deviceID>N2QC8PDLLYJALRQ2VYO3HU891</n0:deviceID>
        <n0:timeStart>2012-08-27T16:30:06.339+05:30</n0:timeStart>
        <n0:timeEnd>2012-08-27T16:38:42.158+05:30</n0:timeEnd>
        <n0:username>8969820824</n0:username>
        <n0:userID>$userId$</n0:userID>
        <n0:instanceID>$instanceId$</n0:instanceID>
        <cc:appVersion>v2.0.0alpha (990ba3-e6e3c5-unvers-2.1.0-Nokia/S40-native-input) #48 b:2012-Jul-26 r:2012-Jul-28</cc:appVersion>
    </n0:meta>
    <n1:case case_id="$caseId$" date_modified="2012-08-27T16:38:42.158+05:30" user_id="$userId$" xmlns:n1="http://commcarehq.org/case/transaction/v2">
        <n1:update>
            <n1:family_planning_type>ppiud_at_delivery</n1:family_planning_type>
            <n1:last_visit_type>eb</n1:last_visit_type>
            <n1:date_last_visit>2012-08-27</n1:date_last_visit>

            <n1:complications>yes</n1:complications>
            <n1:date_eb_1>2012-08-27</n1:date_eb_1>
            <n1:date_eb_2>2012-08-27</n1:date_eb_2>
            <n1:date_eb_3>2012-08-27</n1:date_eb_3>
            <n1:date_eb_4>2012-08-27</n1:date_eb_4>
            <n1:date_eb_5>2012-08-27</n1:date_eb_5>
            <n1:date_eb_6>2012-08-27</n1:date_eb_6>

            <n1:date_next_eb>2012-10-22</n1:date_next_eb>

            <n1:date_next_cf>2012-11-22</n1:date_next_cf>
        </n1:update>
    </n1:case>
    <eb_visit_num>1</eb_visit_num>
    <num_children>1</num_children>
    <children>$child1caseId$</children>
    <child_info>
        <cid>$child1caseId$</cid>
        <index>0</index>
        <n2:case case_id="$child1caseId$" date_modified="2012-08-27T16:38:42.158+05:30" user_id="$userId$" xmlns:n2="http://commcarehq.org/case/transaction/v2">
            <n2:update>
                <n2:bcg_date>2012-07-24</n2:bcg_date>
                <n2:opv_0_date>2012-07-24</n2:opv_0_date>
                <n2:hep_b_0_date>2012-07-24</n2:hep_b_0_date>

                <n2:case_name>Rishi</n2:case_name>
                <n2:dpt_1_date>2012-07-24</n2:dpt_1_date>
                <n2:dpt_2_date>2012-07-24</n2:dpt_2_date>
                <n2:dpt_3_date>2012-07-24</n2:dpt_3_date>
                <n2:hep_b_1_date>2012-07-24</n2:hep_b_1_date>
                <n2:hep_b_2_date>2012-07-24</n2:hep_b_2_date>
                <n2:hep_b_3_date>2012-07-24</n2:hep_b_3_date>
                <n2:opv_1_date>2012-07-24</n2:opv_1_date>
                <n2:opv_2_date>2012-07-24</n2:opv_2_date>
                <n2:opv_3_date>2012-07-24</n2:opv_3_date>


            </n2:update>
        </n2:case>
        <display_child>OK</display_child>
        <name_update>yes</name_update>
        <child_name>Rishi</child_name>

        <add_vaccinations>yes</add_vaccinations>
        <baby_dpt1>yes</baby_dpt1>
        <baby_dpt2>yes</baby_dpt2>
        <baby_dpt3>yes</baby_dpt3>
        <baby_hep_b_1>yes</baby_hep_b_1>
        <baby_hep_b_2>yes</baby_hep_b_2>
        <baby_hep_b_3>yes</baby_hep_b_3>
        <baby_opv1>yes</baby_opv1>
        <baby_opv2>yes</baby_opv2>
        <baby_opv3>yes</baby_opv3>

        <more_feeding_less_six>yes</more_feeding_less_six>
        <not_breasfeeding>yes</not_breasfeeding>
        <treated_less_six>yes</treated_less_six>

        <breastfeeding>yes</breastfeeding>
        <water_or_milk>yes</water_or_milk>
        <tea_other>no</tea_other>
        <eating>no</eating>
        <counsel_only_milk>yes</counsel_only_milk>
        <emptying>yes</emptying>
        <on_demand>yes</on_demand>
        <at_night>yes</at_night>
        <counsel_adequate_bf>yes</counsel_adequate_bf>
        <feeding_bottle>yes</feeding_bottle>
        <counsel_stop_bottle>yes</counsel_stop_bottle>
        <recent_fever>no</recent_fever>
        <add_vaccinations>yes</add_vaccinations>
        <baby_bcg>yes</baby_bcg>
        <baby_opv0>yes</baby_opv0>
        <baby_hep_b_0>yes</baby_hep_b_0>
    </child_info>

    <date_iud_adopted>2013-02-25</date_iud_adopted>
    <date_last_inj>2013-02-25</date_last_inj>
    <next_inj_calc>2013-02-25</next_inj_calc>

    <ask_ppiud>yes</ask_ppiud>
    <aware_of_failure>yes</aware_of_failure>
    <bleeding>yes</bleeding>

    <abdominal_pain>yes</abdominal_pain>

    <condoms>yes</condoms>
    <counsel_follow_up_ppiud>yes</counsel_follow_up_ppiud>
    <counsel_follow_up_pptl>yes</counsel_follow_up_pptl>
    <counsel_menstrual_cycle>yes</counsel_menstrual_cycle>

    <counsel_time_iud>yes</counsel_time_iud>


    <why_no_ppffp>refused</why_no_ppffp>
    <counsel_ppfp>yes</counsel_ppfp>
    <adopt_immediately>yes</adopt_immediately>
    <ppfp_interest>1</ppfp_interest>
    <counsel_methods>yes</counsel_methods>

    <discharge>yes</discharge>
    <distension>yes</distension>
    <menstrual_irregularity>yes</menstrual_irregularity>
    <fever>yes</fever>
    <have_condoms>yes</have_condoms>
    <headaches>yes</headaches>
    <high_bp>yes</high_bp>
    <inj_menstrual_irregularity>yes</inj_menstrual_irregularity>
    <injectable>yes</injectable>
    <intend_to_continue>yes</intend_to_continue>
    <interval_ppfp_interest>yes</interval_ppfp_interest>



    <iud>yes</iud>
    <iud_counsel_placement>yes</iud_counsel_placement>
    <iud_counsel_hospital>yes</iud_counsel_hospital>
    <iud_counsel_screening>yes</iud_counsel_screening>
    <iud_counsel_side_effects>yes</iud_counsel_side_effects>
    <iud_counsel_follow_up>yes</iud_counsel_follow_up>
    <iud_counsel_duration>yes</iud_counsel_duration>
    <iud_adopted>yes</iud_adopted>


    <ocp>yes</ocp>
    <ocp_continue>yes</ocp_continue>
    <ocp_counsel_regularity>yes</ocp_counsel_regularity>
    <pain_swelling>yes</pain_swelling>
    <pain_urination>yes</pain_urination>
    <ppiud_abdominal_pain>yes</ppiud_abdominal_pain>
    <ppiud_bleeding>yes</ppiud_bleeding>
    <ppiud_discharge>yes</ppiud_discharge>
    <ppiud_fever>yes</ppiud_fever>
    <ppiud_problems>yes</ppiud_problems>
    <pptl_abdominal_pain>yes</pptl_abdominal_pain>
    <pptl_pain_surgery>yes</pptl_pain_surgery>
    <pptl_problems>yes</pptl_problems>

    <referral_needed>OK</referral_needed>
    <regular_periods>yes</regular_periods>

    <tablets_received>yes</tablets_received>
    <taken_as_prescribed>yes</taken_as_prescribed>
    <tl>yes</tl>
    <tl_adopted>yes</tl_adopted>
    <tl_consel_incentives>yes</tl_consel_incentives>
    <tl_counsel_follow_up>yes</tl_counsel_follow_up>
    <tl_counsel_hospital>yes</tl_counsel_hospital>
    <tl_counsel_irreversible>yes</tl_counsel_irreversible>
    <tl_counsel_screening>yes</tl_counsel_screening>
    <tl_counsel_side_effects>yes</tl_counsel_side_effects>
    <tl_counsel_timing>yes</tl_counsel_timing>
    <understand_tablets>yes</understand_tablets>

    <using_correctly>yes</using_correctly>
    <where_replace>yes</where_replace>

    <within_42>yes</within_42>

    <date_tl_adopted>2012-08-07</date_tl_adopted>

    <success>OK</success>
    <next_inj_calc />
    <temp>
        <ebf_visit days="14">2012-08-07</ebf_visit>
        <ebf_visit days="28">2012-08-21</ebf_visit>
        <ebf_visit days="60">2012-09-22</ebf_visit>
        <ebf_visit days="90">2012-10-22</ebf_visit>
        <ebf_visit days="120">2012-11-21</ebf_visit>
        <ebf_visit days="150">2012-12-21</ebf_visit>
        <cf_visit days="183">2013-01-23</cf_visit>
        <cf_visit days="213">2013-02-22</cf_visit>
        <cf_visit days="243">2013-03-24</cf_visit>
        <cf_visit days="274">2013-04-24</cf_visit>
        <cf_visit days="365">2013-07-24</cf_visit>
        <cf_visit days="457">2013-10-24</cf_visit>
        <cf_visit days="548">2014-01-23</cf_visit>
    </temp>
    <nextvisit>OK</nextvisit>
    <nextvisittype>ebf</nextvisittype>
    <addval>2012-07-24</addval>
</data>