<?xml version='1.0' ?>
<data uiVersion="1" version="1" name="Growth Monitoring" xmlns:jrm="http://dev.commcarehq.org/jr/xforms" xmlns:cc="http://commcarehq.org/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/growth_monitoring">
    <n0:meta xmlns:n0="http://openrosa.org/jr/xforms">
        <n0:deviceID>5IE0SKCUZK768X5JTM2NA4594</n0:deviceID>
        <n0:timeStart>2014-01-19T15:31:25.989+05:30</n0:timeStart>
        <n0:timeEnd>2014-01-19T15:31:46.067+05:30</n0:timeEnd>
        <n0:username>9973168200</n0:username>
        <n0:userID>$userId$</n0:userID>
        <n0:instanceID>$instanceId$</n0:instanceID>
        <cc:appVersion>v2.9.0 (6b1e95-e699cd-unvers-2.1.0-Nokia/S40-native-input) build 23681 App #6 b:2013-Sep-30 r:2013-Nov-16</cc:appVersion>
    </n0:meta>
    <n1:case case_id="$child1caseId$" date_modified="2014-01-19T15:31:46.067+05:30" user_id="$userId$" xmlns:n1="http://commcarehq.org/case/transaction/v2">
        <n1:update>
            <n1:current_growth>growth_normal</n1:current_growth>
            <n1:last_growth_1>growth_normal</n1:last_growth_1>
            <n1:last_growth_2 />
            <n1:last_growth_3 />
            <n1:current_weight_date>2014-01-19</n1:current_weight_date>
            <n1:last_weight_date>2013-12-09</n1:last_weight_date>
            <n1:current_weight>5</n1:current_weight>
            <n1:last_weight>3</n1:last_weight>
            <n1:age_last_weight>0</n1:age_last_weight>
            <n1:age_current_weight>2</n1:age_current_weight>
        </n1:update>
    </n1:case>
    <take_weight>yes</take_weight>
    <child_weight>5.0</child_weight>
    <show_grade>OK</show_grade>
    <success>OK</success>
    <calc_grade>-1</calc_grade>
    <calc_growth>growth_normal</calc_growth>
    <child_gender>2</child_gender>
    <child_age>2</child_age>
    <dob>2013-11-25</dob>
    <gender>male</gender>
    <change_from_normal>no</change_from_normal>
    <change_from_muw>no</change_from_muw>
    <change_from_suw>no</change_from_suw>
</data>