<?xml version='1.0' ?>
<data uiVersion="1" version="1" name="6. Migrate In" xmlns:jrm="http://dev.commcarehq.org/jr/xforms" xmlns:cc="http://commcarehq.org/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/migrate_in">
    <n0:meta xmlns:n0="http://openrosa.org/jr/xforms">
        <n0:deviceID>TMQZ23DYYZ6XKOLFWEY2QRZ60</n0:deviceID>
        <n0:timeStart>2012-09-07T11:22:06.338+05:30</n0:timeStart>
        <n0:timeEnd>2012-09-07T11:22:45.106+05:30</n0:timeEnd>
        <n0:username>9973168102</n0:username>
        <n0:userID>$userId$</n0:userID>
        <n0:instanceID>$instanceId$</n0:instanceID>
        <cc:appVersion>v2.0.0alpha (990ba3-e6e3c5-unvers-2.1.0-Nokia/S40-native-input) #48 b:2012-Jul-26 r:2012-Jul-28</cc:appVersion>
    </n0:meta>
    <referral_info />
    <n1:case case_id="$caseId$" date_modified="2012-09-07T11:22:45.106+05:30" user_id="$userId$" xmlns:n1="http://commcarehq.org/case/transaction/v2">
        <n1:update>
            <n1:migrated_status>not_migrated</n1:migrated_status>
            <n1:status>migrate_in</n1:status>
        </n1:update>
    </n1:case>
    <date_learned>2012-09-07</date_learned>
    <date_arrived>2012-09-05</date_arrived>
    <preg_status>delivered</preg_status>
    <date_of_delivery>2012-03-26</date_of_delivery>
    <success>OK</success>
    <name />
</data>