<?xml version='1.0' ?>
<data uiVersion="1" version="1" name="5. Migrate Out" xmlns:jrm="http://dev.commcarehq.org/jr/xforms" xmlns:cc="http://commcarehq.org/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/migrate_out">
    <n0:meta xmlns:n0="http://openrosa.org/jr/xforms">
        <n0:deviceID>W6XBHIJ1X9E2MO0EHWAZ312D0</n0:deviceID>
        <n0:timeStart>2012-08-29T01:47:47.340+05:30</n0:timeStart>
        <n0:timeEnd>2012-08-29T01:48:33.317+05:30</n0:timeEnd>
        <n0:username>9973189939</n0:username>
        <n0:userID>$userId$</n0:userID>
        <n0:instanceID>$instanceId$</n0:instanceID>
        <cc:appVersion>v2.0.0alpha (990ba3-e6e3c5-unvers-2.1.0-Nokia/S40-native-input) #48 b:2012-Jul-26 r:2012-Jul-28</cc:appVersion>
    </n0:meta>
    <n1:case case_id="$caseId$" date_modified="2012-08-29T01:48:33.317+05:30" user_id="$userId$" xmlns:n1="http://commcarehq.org/case/transaction/v2">
        <n1:update>
            <n1:migrated_status>migrated</n1:migrated_status>
            <n1:migrate_out_date>2012-07-24</n1:migrate_out_date>
            <n1:status>migrate_out</n1:status>
        </n1:update>
    </n1:case>
    <date_learned>2012-07-25</date_learned>
    <date_left>2012-07-24</date_left>
    <note_given>no</note_given>
    <success>OK</success>
    <name />
</data>