<?xml version="1.0"?>
<data xmlns:jrm="http://dev.commcarehq.org/jr/xforms" xmlns:cc="http://commcarehq.org/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/mother_edit" uiVersion="1" version="2" name="Mother Edit">
    <n0:meta xmlns:n0="http://openrosa.org/jr/xforms">
        <n0:deviceID>AASR2CK0DQDJ637FJNWXR2QAJ</n0:deviceID>
        <n0:timeStart>2013-07-04T12:15:18.179+05:30</n0:timeStart>
        <n0:timeEnd>2013-07-04T12:18:21.730+05:30</n0:timeEnd>
        <n0:username>matt.test</n0:username>
        <n0:userID>$userId$</n0:userID>
        <n0:instanceID>$instanceId$</n0:instanceID>
        <cc:appVersion>v2.6.1 (e3d772-33164b-unvers-2.1.0-Nokia/S40-native-input) build 139 App #4 b:2013-Jul-03 r:2013-Jul-03</cc:appVersion>
    </n0:meta>
    <referral_info/>
    <n1:case xmlns:n1="http://commcarehq.org/case/transaction/v2" case_id="$caseId$" date_modified="2013-07-04T12:18:21.730+05:30" user_id="$userId$">
        <n1:update>
            <n1:case_name>Due list 31</n1:case_name>
            <n1:mother_name>Due list 31</n1:mother_name>
            <n1:mother_dob>1981-06-01</n1:mother_dob>
            <n1:mobile_number>2111111111</n1:mobile_number>
            <n1:ward_number>42</n1:ward_number>
            <n1:age>11</n1:age>
        </n1:update>
    </n1:case>
    <update_mother_name>yes</update_mother_name>
    <update_hh_number>no</update_hh_number>
    <update_family_number>no</update_family_number>
    <update_ward_number>yes</update_ward_number>
    <update_husband_name>no</update_husband_name>
    <update_mother_dob>yes</update_mother_dob>
    <update_mobile_number>yes</update_mobile_number>
    <update_mobile_number_whose>no</update_mobile_number_whose>
    <success>OK</success>
</data>