<?xml version='1.0' ?>
<data uiVersion="1" version="2" name="Move beneficiary" xmlns:cc="http://commcarehq.org/xforms" xmlns="http://bihar.commcarehq.org/tools/move_beneficiary">
    <n0:meta xmlns:n0="http://openrosa.org/jr/xforms">
        <n0:deviceID>DCEJJKMEEFTW8VBRRIAZDEJ0O</n0:deviceID>
        <n0:timeStart>2013-07-04T16:59:55.286+05:30</n0:timeStart>
        <n0:timeEnd>2013-07-04T17:05:40.710+05:30</n0:timeEnd>
        <n0:username>matt.test</n0:username>
        <n0:userID>$userId$</n0:userID>
        <n0:instanceID>$instanceId$</n0:instanceID>
        <cc:appVersion>v2.6.1 (e3d772-33164b-unvers-2.1.0-Nokia/S40-native-input) build 137 App #4 b:2013-Jul-03 r:2013-Jul-03</cc:appVersion>
    </n0:meta>
    <n1:case case_id="$caseId$" date_modified="2013-07-04T17:05:40.710+05:30" user_id="$userId$" xmlns:n1="http://commcarehq.org/case/transaction/v2" />
    <confirm_move>yes</confirm_move>
    <new_ward>11</new_ward>
    <new_awcc>111</new_awcc>
    <confirm_again>yes</confirm_again>
    <success>OK</success>
</data>