<?xml version='1.0' ?>
<data uiVersion="1" version="1" name="PNC" xmlns:cc="http://commcarehq.org/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/pnc">
    <n0:meta xmlns:n0="http://openrosa.org/jr/xforms">
        <n0:deviceID>ZEOKK6OIT66WM5MDIZKEUVSEJ</n0:deviceID>
        <n0:timeStart>2012-10-25T15:05:54.954+05:30</n0:timeStart>
        <n0:timeEnd>2012-10-25T15:07:16.844+05:30</n0:timeEnd>
        <n0:username>8969814973</n0:username>
        <n0:userID>$userId$</n0:userID>
        <n0:instanceID>$instanceId$</n0:instanceID>
        <cc:appVersion>v2.0.0alpha (2b6e13-e6e3c5-unvers-2.1.0-Nokia/S40-native-input) #40 b:2012-Jul-17 r:2012-Jul-25</cc:appVersion>
    </n0:meta>
    <n1:case case_id="$caseId$" date_modified="2012-10-25T15:07:16.844+05:30" user_id="$userId$" xmlns:n1="http://commcarehq.org/case/transaction/v2">
        <n1:update>
            <n1:family_planning_type>no_fp_adopted_at_delivery</n1:family_planning_type>
            <n1:first_pnc_time>within_seven_days</n1:first_pnc_time>
            <n1:last_visit_type>pnc</n1:last_visit_type>
            <n1:date_last_visit>2012-10-25</n1:date_last_visit>
            <n1:date_pnc_1>2012-10-25</n1:date_pnc_1>
            <n1:pnc_1_days_late>-230</n1:pnc_1_days_late>
            <n1:date_next_pnc>2012-10-27</n1:date_next_pnc>
            <n1:date_next_eb>2012-11-01</n1:date_next_eb>

            <n1:all_pnc_on_time>yes</n1:all_pnc_on_time>
            <n1:complications>yes</n1:complications>
            <n1:date_pnc_2>2012-10-25</n1:date_pnc_2>
            <n1:date_pnc_3>2012-10-25</n1:date_pnc_3>
            <n1:mother_alive>yes</n1:mother_alive>

            <n1:pnc_1_days_late>4</n1:pnc_1_days_late>

            <n1:pnc_2_days_late>50</n1:pnc_2_days_late>
            <n1:pnc_3_days_late>0</n1:pnc_3_days_late>

        </n1:update>

    </n1:case>
    <pnc_visit_num>1</pnc_visit_num>
    <safe>yes</safe>
    <bleeding>yes</bleeding>
    <fever>yes</fever>
    <adopt_immediately>yes</adopt_immediately>
    <abdominal_pain>yes</abdominal_pain>
    <discharge>yes</discharge>
    <pain_urination>yes</pain_urination>
    <problems_breast>yes</problems_breast>
    <eating_well>yes</eating_well>
    <counsel_materal_comp>yes</counsel_materal_comp>
    <mother_child_alive>0</mother_child_alive>
    <num_children>1</num_children>
    <children>$child1caseId$</children>
    <child_info>
        <cid>$child1caseId$</cid>
        <index>0</index>
        <display_child>OK</display_child>
        <child_alive>no</child_alive>


        <able_expressed_milk>yes</able_expressed_milk>
        <adequate_support>yes</adequate_support>
        <applied_to_stump>yes</applied_to_stump>
        <baby_active>yes</baby_active>
        <breastfeeding_well>yes</breastfeeding_well>
        <child_place_death>Dharbhanga</child_place_death>
        <chld_date_death>2013-01-23</chld_date_death>
        <cord_fallen>yes</cord_fallen>
        <correct_position>yes</correct_position>
        <counsel_cord_care>yes</counsel_cord_care>
        <counsel_exclusive_bf>yes</counsel_exclusive_bf>
        <counsel_express_milk>yes</counsel_express_milk>
        <counsel_skin>yes</counsel_skin>
        <cousel_bf_correct>yes</cousel_bf_correct>
        <demonstrate_expressed>yes</demonstrate_expressed>
        <demonstrate_skin>yes</demonstrate_skin>
        <easy_awake>yes</easy_awake>
        <feed_vigour>yes</feed_vigour>
        <good_latch>yes</good_latch>
        <improvements_bf>yes</improvements_bf>
        <observed_bf>yes</observed_bf>
        <other_milk_to_child>yes</other_milk_to_child>
        <second_observation>yes</second_observation>
        <skin_to_skin>yes</skin_to_skin>
        <warm_to_touch>yes</warm_to_touch>
        <what_applied>chlorohexidine</what_applied>
        <wrapped>yes</wrapped>




        <child_site_death>home</child_site_death>
        <child_died_village>yes</child_died_village>
        <n2:case case_id="$child1caseId$" date_modified="2012-09-21T14:51:19.315+05:30" user_id="$userId$" xmlns:n2="http://commcarehq.org/case/transaction/v2">
            <n2:close />
        </n2:case>
    </child_info>


    <congested>yes</congested>
    <counsel_breast>yes</counsel_breast>
    <counsel_follow_up_ppiud>yes</counsel_follow_up_ppiud>
    <counsel_follow_up_pptl>yes</counsel_follow_up_pptl>
    <counsel_increase_food_bf>yes</counsel_increase_food_bf>
    <counsel_methods>yes</counsel_methods>
    <counsel_neonatal_comp>yes</counsel_neonatal_comp>
    <counsel_ppfp>yes</counsel_ppfp>
    <counsel_time_iud>yes</counsel_time_iud>
    <date_death>2012-10-25</date_death>
    <date_iud_adopted>2012-10-25</date_iud_adopted>
    <date_tl_adopted>2012-10-25</date_tl_adopted>
    <death_village>yes</death_village>
    <distension>yes</distension>
    <interval_ppfp_interest>yes</interval_ppfp_interest>
    <iud>yes</iud>
    <iud_adopted>yes</iud_adopted>
    <iud_counsel_duration>yes</iud_counsel_duration>
    <iud_counsel_follow_up>yes</iud_counsel_follow_up>
    <iud_counsel_hospital>yes</iud_counsel_hospital>
    <iud_counsel_placement>yes</iud_counsel_placement>
    <iud_counsel_screening>yes</iud_counsel_screening>
    <iud_counsel_side_effects>yes</iud_counsel_side_effects>
    <other_issues>yes</other_issues>
    <painful_nipples>yes</painful_nipples>
    <pc_complete_referral_needed>OK</pc_complete_referral_needed>
    <place_death>test</place_death>
    <ppiud_abdominal_pain>yes</ppiud_abdominal_pain>
    <ppiud_bleeding>yes</ppiud_bleeding>
    <ppiud_discharge>yes</ppiud_discharge>
    <ppiud_fever>yes</ppiud_fever>
    <ppiud_problems>yes</ppiud_problems>
    <pptl_abdominal_pain>yes</pptl_abdominal_pain>
    <pptl_excessive_bleeding>yes</pptl_excessive_bleeding>
    <pptl_pain_surgery>yes</pptl_pain_surgery>
    <pptl_problems>yes</pptl_problems>
    <preterm>OK</preterm>
    <referral_needed>OK</referral_needed>
    <site_death>hospital_death</site_death>
    <tl>yes</tl>
    <tl_adopted>yes</tl_adopted>
    <tl_consel_incentives>yes</tl_consel_incentives>
    <tl_counsel_follow_up>yes</tl_counsel_follow_up>
    <tl_counsel_hospital>yes</tl_counsel_hospital>
    <tl_counsel_irreversible>yes</tl_counsel_irreversible>
    <tl_counsel_screening>yes</tl_counsel_screening>
    <tl_counsel_side_effects>yes</tl_counsel_side_effects>
    <tl_counsel_timing>yes</tl_counsel_timing>
    <why_no_ppffp>doctor_unavailable</why_no_ppffp>
    <ppfp_interest>0</ppfp_interest>
    <success>OK</success>
    <temp>
        <ebf_visit days="14">2012-11-01</ebf_visit>
        <ebf_visit days="28">2012-11-15</ebf_visit>
        <ebf_visit days="60">2012-12-17</ebf_visit>
        <ebf_visit days="90">2013-01-16</ebf_visit>
        <ebf_visit days="120">2013-02-15</ebf_visit>
        <ebf_visit days="150">2013-03-17</ebf_visit>
    </temp>
    <nextvisit>OK</nextvisit>
    <nextvisittype>pnc</nextvisittype>
    <addval>2012-10-18</addval>
</data>