<?xml version='1.0' ?>
<data uiVersion="1" version="1" name="Registration" xmlns:cc="http://commcarehq.org/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/registration">
<n0:meta xmlns:n0="http://openrosa.org/jr/xforms">
<n0:deviceID>BB9E7WYIA186LDGHRYDFZBQF6</n0:deviceID>
<n0:timeStart>2013-01-28T11:01:14.759+05:30</n0:timeStart>
<n0:timeEnd>2013-01-28T11:10:12.236+05:30</n0:timeEnd>
<n0:username>8969820653</n0:username>
<n0:userID>$userId$</n0:userID>
<n0:instanceID>$instanceId$</n0:instanceID>
<cc:appVersion>v2.0.0alpha (990ba3-e6e3c5-unvers-2.1.0-Nokia/S40-native-input) #48 b:2012-Jul-26 r:2012-Jul-28</cc:appVersion>
</n0:meta>
<n1:case case_id="$caseId$" date_modified="2013-01-28T11:10:12.236+05:30" user_id="$userId$" xmlns:n1="http://commcarehq.org/case/transaction/v2">
<n1:update>
<n1:status>active</n1:status>
<n1:mobile_number />
<n1:mother_dob>1988-06-01</n1:mother_dob>
<n1:num_boys>1</n1:num_boys>
<n1:add>2012-02-14</n1:add>
<n1:last_visit_type>reg</n1:last_visit_type>
<n1:date_last_visit>2013-01-28</n1:date_last_visit>
<n1:family_planning_type>no_fp_adopted_at_delivery</n1:family_planning_type>
<n1:edd />
<n1:age>24</n1:age>
<n1:lmp />
<n1:birth_place>public</n1:birth_place>
<n1:how_many_children>1</n1:how_many_children>
<n1:eats_meat>no</n1:eats_meat>
<n1:enrolled_in_kilkari>no</n1:enrolled_in_kilkari>
<n1:interest_in_kilkari>no</n1:interest_in_kilkari>
<n1:date_next_cf>2013-02-13</n1:date_next_cf>
</n1:update>
<n1:close />
</n1:case>
<jsy_beneficiary>no</jsy_beneficiary>
<display_name>OK</display_name>
<age_est_trigger>OK</age_est_trigger>
<age_est>24</age_est>
<children>yes</children>
<num_girls>0</num_girls>
<num_boys>1</num_boys>
<education>metric</education>
<resident>resident</resident>
<vegetarian>no</vegetarian>
<enrolled_in_kilkari>no</enrolled_in_kilkari>
<interest_in_kilkari>no</interest_in_kilkari>
<is_pregnant>no</is_pregnant>
<last_preg_full_term>yes</last_preg_full_term>
<last_preg_c_section>no</last_preg_c_section>
<recently_delivered>yes</recently_delivered>
<how_many_children>1</how_many_children>
<num_children>1</num_children>
<child_dob>2012-02-14</child_dob>
<child_info>
<n2:case case_id="$child1caseId$" date_modified="2013-01-28T11:10:12.236+05:30" user_id="$userId$" xmlns:n2="http://commcarehq.org/case/transaction/v2">
<n2:create>
<n2:case_type>cc_bihar_newborn</n2:case_type>
<n2:owner_id>89fda0284e008d2e0c980fb13fbe1e82</n2:owner_id>
<n2:case_name>&#2352;&#2375;&#2326;&#2366; &#2342;&#2375;&#2357;&#2368; &#2325;&#2366; &#2348;&#2375;&#2335;&#2366;</n2:case_name>
</n2:create>
<n2:update>

<n2:gender>male</n2:gender>

<n2:dob>2012-02-14</n2:dob>


<n2:bcg_date>2012-02-14</n2:bcg_date>
<n2:birth_status>2012-02-14</n2:birth_status>
<n2:dpt_1_date>2012-02-14</n2:dpt_1_date>
<n2:dpt_2_date>2012-02-14</n2:dpt_2_date>
<n2:dpt_3_date>2012-02-14</n2:dpt_3_date>
<n2:hep_b_0_date>2012-02-14</n2:hep_b_0_date>
<n2:hep_b_1_date>2012-02-14</n2:hep_b_1_date>
<n2:hep_b_2_date>2012-02-14</n2:hep_b_2_date>
<n2:hep_b_3_date>2012-02-14</n2:hep_b_3_date>
<n2:measles_date>2012-02-14</n2:measles_date>

<n2:opv_0_date>2012-02-14</n2:opv_0_date>
<n2:opv_1_date>2012-02-14</n2:opv_1_date>
<n2:opv_2_date>2012-02-14</n2:opv_2_date>
<n2:opv_3_date>2012-02-14</n2:opv_3_date>
<n2:vit_a_1_date>2012-02-14</n2:vit_a_1_date>




</n2:update>
<n2:index>
<n2:mother_id case_type="cc_bihar_pregnancy">$caseId$</n2:mother_id>
</n2:index>
</n2:case>
<child_have_a_name>yes</child_have_a_name>
<child_name>&#2348;&#2375;&#2335;&#2366;</child_name>
<display_child_name>OK</display_child_name>

<gender>male</gender>

<weight>2.5</weight>
<abnormalities>no</abnormalities>


<add_vaccinations>no</add_vaccinations>
<baby_bcg>no</baby_bcg>
<baby_dpt1>no</baby_dpt1>
<baby_dpt2>no</baby_dpt2>
<baby_dpt3>no</baby_dpt3>
<baby_hep_b_0>no</baby_hep_b_0>
<baby_hep_b_1>no</baby_hep_b_1>
<baby_hep_b_2>no</baby_hep_b_2>
<baby_hep_b_3>no</baby_hep_b_3>
<baby_measles>no</baby_measles>
<baby_opv0>no</baby_opv0>
<baby_opv1>no</baby_opv1>
<baby_opv2>no</baby_opv2>
<baby_opv3>no</baby_opv3>
<baby_vita1>no</baby_vita1>




</child_info>
<delivery_nature>vaginal</delivery_nature>
<where_born>hospital</where_born>
<which_hospital>district_hospital</which_hospital>
<in_district>no</in_district>
<other_district>&#2350;&#2343;&#2375;&#2346;&#2369;&#2352;&#2366;</other_district>
<jsy_money>yes</jsy_money>
<complications>no</complications>
<referral_prompt />
<other_conditions />
<used_fp>no</used_fp>
<good_to_register>yes</good_to_register>
<success>OK</success>
<dob_est />
<age_calc>24</age_calc>
<lmp_calc />
<edd_calc />
<nextvisit>OK</nextvisit>
<nextvisittype>cf</nextvisittype>
<temp>
<cf_visit days="183">2012-08-15</cf_visit>
<cf_visit days="213">2012-09-14</cf_visit>
<cf_visit days="243">2012-10-14</cf_visit>
<cf_visit days="274">2012-11-14</cf_visit>
<cf_visit days="365">2013-02-13</cf_visit>
<cf_visit days="457">2013-05-16</cf_visit>
<cf_visit days="548">2013-08-15</cf_visit>
</temp>
<age_calc_adj>-1</age_calc_adj>
</data>