<?xml version='1.0' ?>
<data uiVersion="1" version="1" name="Registration" xmlns:cc="http://commcarehq.org/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/registration">
    <n0:meta xmlns:n0="http://openrosa.org/jr/xforms">
        <n0:deviceID>OUVDUHR90BVKVRXBXBVKT4LU3</n0:deviceID>
        <n0:timeStart>2012-08-14T14:17:41.811Z</n0:timeStart>
        <n0:timeEnd>2012-08-14T14:21:38.048Z</n0:timeEnd>
        <n0:username>8969821683</n0:username>
        <n0:userID>$userId$</n0:userID>
        <n0:instanceID>$instanceId$</n0:instanceID>
        <cc:appVersion>v2.0.0alpha (990ba3-e6e3c5-unvers-2.1.0-Nokia/S40-native-input) #48 b:2012-Jul-26 r:2012-Jul-28</cc:appVersion>
    </n0:meta>
    <n1:case case_id="$caseId$" date_modified="2012-08-14T14:21:38.048Z" user_id="$userId$" xmlns:n1="http://commcarehq.org/case/transaction/v2">
        <n1:update>
            <n1:status>active</n1:status>
            <n1:mobile_number />
            <n1:mother_dob>1985-06-01</n1:mother_dob>
            <n1:num_boys>1</n1:num_boys>
            <n1:add />
            <n1:last_visit_type>reg</n1:last_visit_type>
            <n1:date_last_visit>2012-08-14</n1:date_last_visit>
            <n1:family_planning_type />
            <n1:edd>2012-09-05</n1:edd>
            <n1:age>27</n1:age>
            <n1:lmp>2011-11-30</n1:lmp>
            <n1:last_preg_tt>yes</n1:last_preg_tt>
            <n1:birth_place>public</n1:birth_place>
            <n1:how_many_children />
            <n1:eats_meat>yes</n1:eats_meat>
            <n1:enrolled_in_kilkari>no</n1:enrolled_in_kilkari>
            <n1:interest_in_kilkari>no</n1:interest_in_kilkari>
            <n1:date_next_bp>2012-08-14</n1:date_next_bp>
        </n1:update>
        <n1:close />
    </n1:case>
    <jsy_beneficiary>yes</jsy_beneficiary>
    <display_name>OK</display_name>
    <age_est_trigger>OK</age_est_trigger>
    <age_est>27</age_est>
    <children>yes</children>
    <num_girls>3</num_girls>
    <num_boys>1</num_boys>
    <education>illiterate</education>
    <resident>resident</resident>
    <vegetarian>yes</vegetarian>
    <enrolled_in_kilkari>no</enrolled_in_kilkari>
    <interest_in_kilkari>no</interest_in_kilkari>
    <is_pregnant>yes</is_pregnant>
    <urine_test>yes</urine_test>
    <lmp_known>no</lmp_known>
    <edd_known>yes</edd_known>
    <edd>2012-09-05</edd>
    <preg_desired>yes</preg_desired>
    <last_preg>2</last_preg>
    <last_preg_full_term>yes</last_preg_full_term>
    <last_preg_c_section>no</last_preg_c_section>
    <num_children>0</num_children>
    <referral_prompt />
    <other_conditions />
    <used_fp>no</used_fp>
    <good_to_register>yes</good_to_register>
    <success>OK</success>
    <dob_est />
    <age_calc>27</age_calc>
    <lmp_calc>2011-11-30</lmp_calc>
    <edd_calc>2012-09-05</edd_calc>
    <nextvisit_bp>OK</nextvisit_bp>
    <nextvisittype>bp</nextvisittype>
    <temp />
    <age_calc_adj>0</age_calc_adj>
</data>