INSERT INTO report.location_dimension (state, district, block)
VALUES
('UNKNOWN', 'UNKNOWN', 'UNKNOWN'),
('BIHAR', 'SAHARSA', 'NAUHATTA'),
('BIHAR', 'SAHARSA', 'SATAR KATAIYA'),
('BIHAR', 'SAHARSA', 'MAHISHI'),
('BIHAR', 'SAHARSA', 'KAHARA'),
('BIHAR', 'SAHARSA', 'SAOR BAZAR'),
('BIHAR', 'SAHARSA', 'PATARGHAT'),
('BIHAR', 'SAHARSA', 'SONBARSA'),
('BIHAR', 'SAHARSA', 'SIMRI BAKHTIARPUR'),
('BIHAR', 'SAHARSA', 'SALKHUA'),
('BIHAR', 'SAHARSA', 'BANMA ITAHRI');