package org.motechproject.care.reporting.domain.dimension;

// Generated Jun 3, 2013 2:41:26 PM by Hibernate Tools 3.4.0.CR1

import org.motechproject.care.reporting.domain.measure.*;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ChildCase generated by hbm2java
 */
@Entity
@Table(name = "child_case")
public class ChildCase implements java.io.Serializable {

	private int id;
	private MotherCase motherCase;
	private FlwGroup flwGroup;
	private String caseId;
	private String caseName;
	private Date dateModified;
	private Boolean abnormalities;
	private Boolean addVaccinations;
	private Boolean babyBcg;
	private Boolean babyDpt1;
	private Boolean babyDpt2;
	private Boolean babyDpt3;
	private Boolean babyHepB0;
	private Boolean babyHepB1;
	private Boolean babyHepB2;
	private Boolean babyHepB3;
	private Boolean babyMeasles;
	private Boolean babyOpv0;
	private Boolean babyOpv1;
	private Boolean babyOpv2;
	private Boolean babyOpv3;
	private Boolean babyVita1;
	private String caseType;
	private Date bcgDate;
	private String birthStatus;
	private Date dob;
	private Date dpt1Date;
	private Date dpt2Date;
	private Date dpt3Date;
	private String gender;
	private Date hepB0Date;
	private Date hepB1Date;
	private Date hepB2Date;
	private Date hepB3Date;
	private Date measlesDate;
	private Date opv0Date;
	private Date opv1Date;
	private Date opv2Date;
	private Date opv3Date;
	private Date vitA1Date;
	private Boolean childHaveAName;
	private String childName;
	private BigDecimal weight;
	private Boolean amountGood;
	private String cid;
	private Boolean dal;
	private Boolean eatenCereal;
	private Boolean egg;
	private Boolean fish;
	private Integer index;
	private Boolean meat;
	private Boolean milkCurd;
	private Boolean moreFeedingLessSix;
	private Boolean nameUpdate;
	private String newName;
	private Boolean numberGood;
	private Boolean oilGhee;
	private Boolean recentFever;
	private Boolean treatedLessSix;
	private Boolean atNight;
	private Boolean breastfeeding;
	private Boolean counselAdequateBf;
	private Boolean counselOnlyMilk;
	private Boolean counselStopBottle;
	private Boolean eating;
	private Boolean emptying;
	private Boolean feedingBottle;
	private String notBreasfeeding;
	private Boolean onDemand;
	private Boolean teaOther;
	private Boolean waterOrMilk;
	private Boolean ableExpressedMilk;
	private Boolean adequateSupport;
	private Boolean appliedToStump;
	private Boolean babyActive;
	private Boolean breastfeedingWell;
	private Boolean childAlive;
	private Boolean childDiedVillage;
	private String childPlaceDeath;
	private String childSiteDeath;
	private Date chldDateDeath;
	private Boolean cordFallen;
	private Boolean correctPosition;
	private Boolean counselCordCare;
	private Boolean counselExclusiveBf;
	private Boolean counselExpressMilk;
	private Boolean counselSkin;
	private Boolean couselBfCorrect;
	private Boolean demonstrateExpressed;
	private Boolean demonstrateSkin;
	private Boolean easyAwake;
	private Boolean feedVigour;
	private Boolean goodLatch;
	private Boolean improvementsBf;
	private Boolean observedBf;
	private Boolean otherMilkToChild;
	private Boolean secondObservation;
	private Boolean skinToSkin;
	private Boolean warmToTouch;
	private String whatApplied;
	private Boolean wrapped;
	private Date dptBoosterDate;
	private Date opvBoosterDate;
	private Date dateDeath;
	private Boolean died;
	private Boolean diedVillage;
	private Boolean dupeReg;
	private Boolean finishedContinuum;
	private String siteDeath;
	private Boolean referChild;
	private Set<EbfChildForm> ebfChildForms = new HashSet<EbfChildForm>(0);
	private Set<PncChildForm> pncChildForms = new HashSet<PncChildForm>(0);
	private Set<DeathChildForm> deathChildForms = new HashSet<DeathChildForm>(0);
	private Set<CloseChildForm> closeChildForms = new HashSet<CloseChildForm>(0);
	private Set<ReferChildForm> referChildForms = new HashSet<ReferChildForm>(0);
	private Set<RegistrationChildForm> registrationChildForms = new HashSet<RegistrationChildForm>(
			0);
	private Set<CfChildForm> cfChildForms = new HashSet<CfChildForm>(0);
	private Set<UiChildForm> uiChildForms = new HashSet<UiChildForm>(0);

	public ChildCase() {
	}

	public ChildCase(int id) {
		this.id = id;
	}

	public ChildCase(int id, MotherCase motherCase, FlwGroup flwGroup,
			String caseId, String caseName, Date dateModified,
			Boolean abnormalities, Boolean addVaccinations, Boolean babyBcg,
			Boolean babyDpt1, Boolean babyDpt2, Boolean babyDpt3,
			Boolean babyHepB0, Boolean babyHepB1, Boolean babyHepB2,
			Boolean babyHepB3, Boolean babyMeasles, Boolean babyOpv0,
			Boolean babyOpv1, Boolean babyOpv2, Boolean babyOpv3,
			Boolean babyVita1, String caseType, Date bcgDate,
			String birthStatus, Date dob, Date dpt1Date, Date dpt2Date,
			Date dpt3Date, String gender, Date hepB0Date, Date hepB1Date,
			Date hepB2Date, Date hepB3Date, Date measlesDate, Date opv0Date,
			Date opv1Date, Date opv2Date, Date opv3Date, Date vitA1Date,
			Boolean childHaveAName, String childName, BigDecimal weight,
			Boolean amountGood, String cid, Boolean dal, Boolean eatenCereal,
			Boolean egg, Boolean fish, Integer index, Boolean meat,
			Boolean milkCurd, Boolean moreFeedingLessSix, Boolean nameUpdate,
			String newName, Boolean numberGood, Boolean oilGhee,
			Boolean recentFever, Boolean treatedLessSix, Boolean atNight,
			Boolean breastfeeding, Boolean counselAdequateBf,
			Boolean counselOnlyMilk, Boolean counselStopBottle, Boolean eating,
			Boolean emptying, Boolean feedingBottle, String notBreasfeeding,
			Boolean onDemand, Boolean teaOther, Boolean waterOrMilk,
			Boolean ableExpressedMilk, Boolean adequateSupport,
			Boolean appliedToStump, Boolean babyActive,
			Boolean breastfeedingWell, Boolean childAlive,
			Boolean childDiedVillage, String childPlaceDeath,
			String childSiteDeath, Date chldDateDeath, Boolean cordFallen,
			Boolean correctPosition, Boolean counselCordCare,
			Boolean counselExclusiveBf, Boolean counselExpressMilk,
			Boolean counselSkin, Boolean couselBfCorrect,
			Boolean demonstrateExpressed, Boolean demonstrateSkin,
			Boolean easyAwake, Boolean feedVigour, Boolean goodLatch,
			Boolean improvementsBf, Boolean observedBf,
			Boolean otherMilkToChild, Boolean secondObservation,
			Boolean skinToSkin, Boolean warmToTouch, String whatApplied,
			Boolean wrapped, Date dptBoosterDate, Date opvBoosterDate,
			Date dateDeath, Boolean died, Boolean diedVillage, Boolean dupeReg,
			Boolean finishedContinuum, String siteDeath, Boolean referChild,
			Set<EbfChildForm> ebfChildForms, Set<PncChildForm> pncChildForms,
			Set<DeathChildForm> deathChildForms,
			Set<CloseChildForm> closeChildForms,
			Set<ReferChildForm> referChildForms,
			Set<RegistrationChildForm> registrationChildForms,
			Set<CfChildForm> cfChildForms, Set<UiChildForm> uiChildForms) {
		this.id = id;
		this.motherCase = motherCase;
		this.flwGroup = flwGroup;
		this.caseId = caseId;
		this.caseName = caseName;
		this.dateModified = dateModified;
		this.abnormalities = abnormalities;
		this.addVaccinations = addVaccinations;
		this.babyBcg = babyBcg;
		this.babyDpt1 = babyDpt1;
		this.babyDpt2 = babyDpt2;
		this.babyDpt3 = babyDpt3;
		this.babyHepB0 = babyHepB0;
		this.babyHepB1 = babyHepB1;
		this.babyHepB2 = babyHepB2;
		this.babyHepB3 = babyHepB3;
		this.babyMeasles = babyMeasles;
		this.babyOpv0 = babyOpv0;
		this.babyOpv1 = babyOpv1;
		this.babyOpv2 = babyOpv2;
		this.babyOpv3 = babyOpv3;
		this.babyVita1 = babyVita1;
		this.caseType = caseType;
		this.bcgDate = bcgDate;
		this.birthStatus = birthStatus;
		this.dob = dob;
		this.dpt1Date = dpt1Date;
		this.dpt2Date = dpt2Date;
		this.dpt3Date = dpt3Date;
		this.gender = gender;
		this.hepB0Date = hepB0Date;
		this.hepB1Date = hepB1Date;
		this.hepB2Date = hepB2Date;
		this.hepB3Date = hepB3Date;
		this.measlesDate = measlesDate;
		this.opv0Date = opv0Date;
		this.opv1Date = opv1Date;
		this.opv2Date = opv2Date;
		this.opv3Date = opv3Date;
		this.vitA1Date = vitA1Date;
		this.childHaveAName = childHaveAName;
		this.childName = childName;
		this.weight = weight;
		this.amountGood = amountGood;
		this.cid = cid;
		this.dal = dal;
		this.eatenCereal = eatenCereal;
		this.egg = egg;
		this.fish = fish;
		this.index = index;
		this.meat = meat;
		this.milkCurd = milkCurd;
		this.moreFeedingLessSix = moreFeedingLessSix;
		this.nameUpdate = nameUpdate;
		this.newName = newName;
		this.numberGood = numberGood;
		this.oilGhee = oilGhee;
		this.recentFever = recentFever;
		this.treatedLessSix = treatedLessSix;
		this.atNight = atNight;
		this.breastfeeding = breastfeeding;
		this.counselAdequateBf = counselAdequateBf;
		this.counselOnlyMilk = counselOnlyMilk;
		this.counselStopBottle = counselStopBottle;
		this.eating = eating;
		this.emptying = emptying;
		this.feedingBottle = feedingBottle;
		this.notBreasfeeding = notBreasfeeding;
		this.onDemand = onDemand;
		this.teaOther = teaOther;
		this.waterOrMilk = waterOrMilk;
		this.ableExpressedMilk = ableExpressedMilk;
		this.adequateSupport = adequateSupport;
		this.appliedToStump = appliedToStump;
		this.babyActive = babyActive;
		this.breastfeedingWell = breastfeedingWell;
		this.childAlive = childAlive;
		this.childDiedVillage = childDiedVillage;
		this.childPlaceDeath = childPlaceDeath;
		this.childSiteDeath = childSiteDeath;
		this.chldDateDeath = chldDateDeath;
		this.cordFallen = cordFallen;
		this.correctPosition = correctPosition;
		this.counselCordCare = counselCordCare;
		this.counselExclusiveBf = counselExclusiveBf;
		this.counselExpressMilk = counselExpressMilk;
		this.counselSkin = counselSkin;
		this.couselBfCorrect = couselBfCorrect;
		this.demonstrateExpressed = demonstrateExpressed;
		this.demonstrateSkin = demonstrateSkin;
		this.easyAwake = easyAwake;
		this.feedVigour = feedVigour;
		this.goodLatch = goodLatch;
		this.improvementsBf = improvementsBf;
		this.observedBf = observedBf;
		this.otherMilkToChild = otherMilkToChild;
		this.secondObservation = secondObservation;
		this.skinToSkin = skinToSkin;
		this.warmToTouch = warmToTouch;
		this.whatApplied = whatApplied;
		this.wrapped = wrapped;
		this.dptBoosterDate = dptBoosterDate;
		this.opvBoosterDate = opvBoosterDate;
		this.dateDeath = dateDeath;
		this.died = died;
		this.diedVillage = diedVillage;
		this.dupeReg = dupeReg;
		this.finishedContinuum = finishedContinuum;
		this.siteDeath = siteDeath;
		this.referChild = referChild;
		this.ebfChildForms = ebfChildForms;
		this.pncChildForms = pncChildForms;
		this.deathChildForms = deathChildForms;
		this.closeChildForms = closeChildForms;
		this.referChildForms = referChildForms;
		this.registrationChildForms = registrationChildForms;
		this.cfChildForms = cfChildForms;
		this.uiChildForms = uiChildForms;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mother_id")
	public MotherCase getMotherCase() {
		return this.motherCase;
	}

	public void setMotherCase(MotherCase motherCase) {
		this.motherCase = motherCase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner_id")
	public FlwGroup getFlwGroup() {
		return this.flwGroup;
	}

	public void setFlwGroup(FlwGroup flwGroup) {
		this.flwGroup = flwGroup;
	}

	@Column(name = "case_id", length = 36)
	public String getCaseId() {
		return this.caseId;
	}

	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}

	@Column(name = "case_name")
	public String getCaseName() {
		return this.caseName;
	}

	public void setCaseName(String caseName) {
		this.caseName = caseName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modified", length = 35)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	@Column(name = "abnormalities")
	public Boolean getAbnormalities() {
		return this.abnormalities;
	}

	public void setAbnormalities(Boolean abnormalities) {
		this.abnormalities = abnormalities;
	}

	@Column(name = "add_vaccinations")
	public Boolean getAddVaccinations() {
		return this.addVaccinations;
	}

	public void setAddVaccinations(Boolean addVaccinations) {
		this.addVaccinations = addVaccinations;
	}

	@Column(name = "baby_bcg")
	public Boolean getBabyBcg() {
		return this.babyBcg;
	}

	public void setBabyBcg(Boolean babyBcg) {
		this.babyBcg = babyBcg;
	}

	@Column(name = "baby_dpt1")
	public Boolean getBabyDpt1() {
		return this.babyDpt1;
	}

	public void setBabyDpt1(Boolean babyDpt1) {
		this.babyDpt1 = babyDpt1;
	}

	@Column(name = "baby_dpt2")
	public Boolean getBabyDpt2() {
		return this.babyDpt2;
	}

	public void setBabyDpt2(Boolean babyDpt2) {
		this.babyDpt2 = babyDpt2;
	}

	@Column(name = "baby_dpt3")
	public Boolean getBabyDpt3() {
		return this.babyDpt3;
	}

	public void setBabyDpt3(Boolean babyDpt3) {
		this.babyDpt3 = babyDpt3;
	}

	@Column(name = "baby_hep_b_0")
	public Boolean getBabyHepB0() {
		return this.babyHepB0;
	}

	public void setBabyHepB0(Boolean babyHepB0) {
		this.babyHepB0 = babyHepB0;
	}

	@Column(name = "baby_hep_b_1")
	public Boolean getBabyHepB1() {
		return this.babyHepB1;
	}

	public void setBabyHepB1(Boolean babyHepB1) {
		this.babyHepB1 = babyHepB1;
	}

	@Column(name = "baby_hep_b_2")
	public Boolean getBabyHepB2() {
		return this.babyHepB2;
	}

	public void setBabyHepB2(Boolean babyHepB2) {
		this.babyHepB2 = babyHepB2;
	}

	@Column(name = "baby_hep_b_3")
	public Boolean getBabyHepB3() {
		return this.babyHepB3;
	}

	public void setBabyHepB3(Boolean babyHepB3) {
		this.babyHepB3 = babyHepB3;
	}

	@Column(name = "baby_measles")
	public Boolean getBabyMeasles() {
		return this.babyMeasles;
	}

	public void setBabyMeasles(Boolean babyMeasles) {
		this.babyMeasles = babyMeasles;
	}

	@Column(name = "baby_opv0")
	public Boolean getBabyOpv0() {
		return this.babyOpv0;
	}

	public void setBabyOpv0(Boolean babyOpv0) {
		this.babyOpv0 = babyOpv0;
	}

	@Column(name = "baby_opv1")
	public Boolean getBabyOpv1() {
		return this.babyOpv1;
	}

	public void setBabyOpv1(Boolean babyOpv1) {
		this.babyOpv1 = babyOpv1;
	}

	@Column(name = "baby_opv2")
	public Boolean getBabyOpv2() {
		return this.babyOpv2;
	}

	public void setBabyOpv2(Boolean babyOpv2) {
		this.babyOpv2 = babyOpv2;
	}

	@Column(name = "baby_opv3")
	public Boolean getBabyOpv3() {
		return this.babyOpv3;
	}

	public void setBabyOpv3(Boolean babyOpv3) {
		this.babyOpv3 = babyOpv3;
	}

	@Column(name = "baby_vita1")
	public Boolean getBabyVita1() {
		return this.babyVita1;
	}

	public void setBabyVita1(Boolean babyVita1) {
		this.babyVita1 = babyVita1;
	}

	@Column(name = "case_type")
	public String getCaseType() {
		return this.caseType;
	}

	public void setCaseType(String caseType) {
		this.caseType = caseType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "bcg_date", length = 13)
	public Date getBcgDate() {
		return this.bcgDate;
	}

	public void setBcgDate(Date bcgDate) {
		this.bcgDate = bcgDate;
	}

	@Column(name = "birth_status")
	public String getBirthStatus() {
		return this.birthStatus;
	}

	public void setBirthStatus(String birthStatus) {
		this.birthStatus = birthStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dob", length = 13)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dpt_1_date", length = 13)
	public Date getDpt1Date() {
		return this.dpt1Date;
	}

	public void setDpt1Date(Date dpt1Date) {
		this.dpt1Date = dpt1Date;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dpt_2_date", length = 13)
	public Date getDpt2Date() {
		return this.dpt2Date;
	}

	public void setDpt2Date(Date dpt2Date) {
		this.dpt2Date = dpt2Date;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dpt_3_date", length = 13)
	public Date getDpt3Date() {
		return this.dpt3Date;
	}

	public void setDpt3Date(Date dpt3Date) {
		this.dpt3Date = dpt3Date;
	}

	@Column(name = "gender", length = 15)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "hep_b_0_date", length = 13)
	public Date getHepB0Date() {
		return this.hepB0Date;
	}

	public void setHepB0Date(Date hepB0Date) {
		this.hepB0Date = hepB0Date;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "hep_b_1_date", length = 13)
	public Date getHepB1Date() {
		return this.hepB1Date;
	}

	public void setHepB1Date(Date hepB1Date) {
		this.hepB1Date = hepB1Date;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "hep_b_2_date", length = 13)
	public Date getHepB2Date() {
		return this.hepB2Date;
	}

	public void setHepB2Date(Date hepB2Date) {
		this.hepB2Date = hepB2Date;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "hep_b_3_date", length = 13)
	public Date getHepB3Date() {
		return this.hepB3Date;
	}

	public void setHepB3Date(Date hepB3Date) {
		this.hepB3Date = hepB3Date;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "measles_date", length = 13)
	public Date getMeaslesDate() {
		return this.measlesDate;
	}

	public void setMeaslesDate(Date measlesDate) {
		this.measlesDate = measlesDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "opv_0_date", length = 13)
	public Date getOpv0Date() {
		return this.opv0Date;
	}

	public void setOpv0Date(Date opv0Date) {
		this.opv0Date = opv0Date;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "opv_1_date", length = 13)
	public Date getOpv1Date() {
		return this.opv1Date;
	}

	public void setOpv1Date(Date opv1Date) {
		this.opv1Date = opv1Date;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "opv_2_date", length = 13)
	public Date getOpv2Date() {
		return this.opv2Date;
	}

	public void setOpv2Date(Date opv2Date) {
		this.opv2Date = opv2Date;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "opv_3_date", length = 13)
	public Date getOpv3Date() {
		return this.opv3Date;
	}

	public void setOpv3Date(Date opv3Date) {
		this.opv3Date = opv3Date;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "vit_a_1_date", length = 13)
	public Date getVitA1Date() {
		return this.vitA1Date;
	}

	public void setVitA1Date(Date vitA1Date) {
		this.vitA1Date = vitA1Date;
	}

	@Column(name = "child_have_a_name")
	public Boolean getChildHaveAName() {
		return this.childHaveAName;
	}

	public void setChildHaveAName(Boolean childHaveAName) {
		this.childHaveAName = childHaveAName;
	}

	@Column(name = "child_name")
	public String getChildName() {
		return this.childName;
	}

	public void setChildName(String childName) {
		this.childName = childName;
	}

	@Column(name = "weight", precision = 131089, scale = 0)
	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	@Column(name = "amount_good")
	public Boolean getAmountGood() {
		return this.amountGood;
	}

	public void setAmountGood(Boolean amountGood) {
		this.amountGood = amountGood;
	}

	@Column(name = "cid", length = 36)
	public String getCid() {
		return this.cid;
	}

	public void setCid(String cid) {
		this.cid = cid;
	}

	@Column(name = "dal")
	public Boolean getDal() {
		return this.dal;
	}

	public void setDal(Boolean dal) {
		this.dal = dal;
	}

	@Column(name = "eaten_cereal")
	public Boolean getEatenCereal() {
		return this.eatenCereal;
	}

	public void setEatenCereal(Boolean eatenCereal) {
		this.eatenCereal = eatenCereal;
	}

	@Column(name = "egg")
	public Boolean getEgg() {
		return this.egg;
	}

	public void setEgg(Boolean egg) {
		this.egg = egg;
	}

	@Column(name = "fish")
	public Boolean getFish() {
		return this.fish;
	}

	public void setFish(Boolean fish) {
		this.fish = fish;
	}

	@Column(name = "index")
	public Integer getIndex() {
		return this.index;
	}

	public void setIndex(Integer index) {
		this.index = index;
	}

	@Column(name = "meat")
	public Boolean getMeat() {
		return this.meat;
	}

	public void setMeat(Boolean meat) {
		this.meat = meat;
	}

	@Column(name = "milk_curd")
	public Boolean getMilkCurd() {
		return this.milkCurd;
	}

	public void setMilkCurd(Boolean milkCurd) {
		this.milkCurd = milkCurd;
	}

	@Column(name = "more_feeding_less_six")
	public Boolean getMoreFeedingLessSix() {
		return this.moreFeedingLessSix;
	}

	public void setMoreFeedingLessSix(Boolean moreFeedingLessSix) {
		this.moreFeedingLessSix = moreFeedingLessSix;
	}

	@Column(name = "name_update")
	public Boolean getNameUpdate() {
		return this.nameUpdate;
	}

	public void setNameUpdate(Boolean nameUpdate) {
		this.nameUpdate = nameUpdate;
	}

	@Column(name = "new_name")
	public String getNewName() {
		return this.newName;
	}

	public void setNewName(String newName) {
		this.newName = newName;
	}

	@Column(name = "number_good")
	public Boolean getNumberGood() {
		return this.numberGood;
	}

	public void setNumberGood(Boolean numberGood) {
		this.numberGood = numberGood;
	}

	@Column(name = "oil_ghee")
	public Boolean getOilGhee() {
		return this.oilGhee;
	}

	public void setOilGhee(Boolean oilGhee) {
		this.oilGhee = oilGhee;
	}

	@Column(name = "recent_fever")
	public Boolean getRecentFever() {
		return this.recentFever;
	}

	public void setRecentFever(Boolean recentFever) {
		this.recentFever = recentFever;
	}

	@Column(name = "treated_less_six")
	public Boolean getTreatedLessSix() {
		return this.treatedLessSix;
	}

	public void setTreatedLessSix(Boolean treatedLessSix) {
		this.treatedLessSix = treatedLessSix;
	}

	@Column(name = "at_night")
	public Boolean getAtNight() {
		return this.atNight;
	}

	public void setAtNight(Boolean atNight) {
		this.atNight = atNight;
	}

	@Column(name = "breastfeeding")
	public Boolean getBreastfeeding() {
		return this.breastfeeding;
	}

	public void setBreastfeeding(Boolean breastfeeding) {
		this.breastfeeding = breastfeeding;
	}

	@Column(name = "counsel_adequate_bf")
	public Boolean getCounselAdequateBf() {
		return this.counselAdequateBf;
	}

	public void setCounselAdequateBf(Boolean counselAdequateBf) {
		this.counselAdequateBf = counselAdequateBf;
	}

	@Column(name = "counsel_only_milk")
	public Boolean getCounselOnlyMilk() {
		return this.counselOnlyMilk;
	}

	public void setCounselOnlyMilk(Boolean counselOnlyMilk) {
		this.counselOnlyMilk = counselOnlyMilk;
	}

	@Column(name = "counsel_stop_bottle")
	public Boolean getCounselStopBottle() {
		return this.counselStopBottle;
	}

	public void setCounselStopBottle(Boolean counselStopBottle) {
		this.counselStopBottle = counselStopBottle;
	}

	@Column(name = "eating")
	public Boolean getEating() {
		return this.eating;
	}

	public void setEating(Boolean eating) {
		this.eating = eating;
	}

	@Column(name = "emptying")
	public Boolean getEmptying() {
		return this.emptying;
	}

	public void setEmptying(Boolean emptying) {
		this.emptying = emptying;
	}

	@Column(name = "feeding_bottle")
	public Boolean getFeedingBottle() {
		return this.feedingBottle;
	}

	public void setFeedingBottle(Boolean feedingBottle) {
		this.feedingBottle = feedingBottle;
	}

	@Column(name = "not_breasfeeding")
	public String getNotBreasfeeding() {
		return this.notBreasfeeding;
	}

	public void setNotBreasfeeding(String notBreasfeeding) {
		this.notBreasfeeding = notBreasfeeding;
	}

	@Column(name = "on_demand")
	public Boolean getOnDemand() {
		return this.onDemand;
	}

	public void setOnDemand(Boolean onDemand) {
		this.onDemand = onDemand;
	}

	@Column(name = "tea_other")
	public Boolean getTeaOther() {
		return this.teaOther;
	}

	public void setTeaOther(Boolean teaOther) {
		this.teaOther = teaOther;
	}

	@Column(name = "water_or_milk")
	public Boolean getWaterOrMilk() {
		return this.waterOrMilk;
	}

	public void setWaterOrMilk(Boolean waterOrMilk) {
		this.waterOrMilk = waterOrMilk;
	}

	@Column(name = "able_expressed_milk")
	public Boolean getAbleExpressedMilk() {
		return this.ableExpressedMilk;
	}

	public void setAbleExpressedMilk(Boolean ableExpressedMilk) {
		this.ableExpressedMilk = ableExpressedMilk;
	}

	@Column(name = "adequate_support")
	public Boolean getAdequateSupport() {
		return this.adequateSupport;
	}

	public void setAdequateSupport(Boolean adequateSupport) {
		this.adequateSupport = adequateSupport;
	}

	@Column(name = "applied_to_stump")
	public Boolean getAppliedToStump() {
		return this.appliedToStump;
	}

	public void setAppliedToStump(Boolean appliedToStump) {
		this.appliedToStump = appliedToStump;
	}

	@Column(name = "baby_active")
	public Boolean getBabyActive() {
		return this.babyActive;
	}

	public void setBabyActive(Boolean babyActive) {
		this.babyActive = babyActive;
	}

	@Column(name = "breastfeeding_well")
	public Boolean getBreastfeedingWell() {
		return this.breastfeedingWell;
	}

	public void setBreastfeedingWell(Boolean breastfeedingWell) {
		this.breastfeedingWell = breastfeedingWell;
	}

	@Column(name = "child_alive")
	public Boolean getChildAlive() {
		return this.childAlive;
	}

	public void setChildAlive(Boolean childAlive) {
		this.childAlive = childAlive;
	}

	@Column(name = "child_died_village")
	public Boolean getChildDiedVillage() {
		return this.childDiedVillage;
	}

	public void setChildDiedVillage(Boolean childDiedVillage) {
		this.childDiedVillage = childDiedVillage;
	}

	@Column(name = "child_place_death")
	public String getChildPlaceDeath() {
		return this.childPlaceDeath;
	}

	public void setChildPlaceDeath(String childPlaceDeath) {
		this.childPlaceDeath = childPlaceDeath;
	}

	@Column(name = "child_site_death")
	public String getChildSiteDeath() {
		return this.childSiteDeath;
	}

	public void setChildSiteDeath(String childSiteDeath) {
		this.childSiteDeath = childSiteDeath;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "chld_date_death", length = 13)
	public Date getChldDateDeath() {
		return this.chldDateDeath;
	}

	public void setChldDateDeath(Date chldDateDeath) {
		this.chldDateDeath = chldDateDeath;
	}

	@Column(name = "cord_fallen")
	public Boolean getCordFallen() {
		return this.cordFallen;
	}

	public void setCordFallen(Boolean cordFallen) {
		this.cordFallen = cordFallen;
	}

	@Column(name = "correct_position")
	public Boolean getCorrectPosition() {
		return this.correctPosition;
	}

	public void setCorrectPosition(Boolean correctPosition) {
		this.correctPosition = correctPosition;
	}

	@Column(name = "counsel_cord_care")
	public Boolean getCounselCordCare() {
		return this.counselCordCare;
	}

	public void setCounselCordCare(Boolean counselCordCare) {
		this.counselCordCare = counselCordCare;
	}

	@Column(name = "counsel_exclusive_bf")
	public Boolean getCounselExclusiveBf() {
		return this.counselExclusiveBf;
	}

	public void setCounselExclusiveBf(Boolean counselExclusiveBf) {
		this.counselExclusiveBf = counselExclusiveBf;
	}

	@Column(name = "counsel_express_milk")
	public Boolean getCounselExpressMilk() {
		return this.counselExpressMilk;
	}

	public void setCounselExpressMilk(Boolean counselExpressMilk) {
		this.counselExpressMilk = counselExpressMilk;
	}

	@Column(name = "counsel_skin")
	public Boolean getCounselSkin() {
		return this.counselSkin;
	}

	public void setCounselSkin(Boolean counselSkin) {
		this.counselSkin = counselSkin;
	}

	@Column(name = "cousel_bf_correct")
	public Boolean getCouselBfCorrect() {
		return this.couselBfCorrect;
	}

	public void setCouselBfCorrect(Boolean couselBfCorrect) {
		this.couselBfCorrect = couselBfCorrect;
	}

	@Column(name = "demonstrate_expressed")
	public Boolean getDemonstrateExpressed() {
		return this.demonstrateExpressed;
	}

	public void setDemonstrateExpressed(Boolean demonstrateExpressed) {
		this.demonstrateExpressed = demonstrateExpressed;
	}

	@Column(name = "demonstrate_skin")
	public Boolean getDemonstrateSkin() {
		return this.demonstrateSkin;
	}

	public void setDemonstrateSkin(Boolean demonstrateSkin) {
		this.demonstrateSkin = demonstrateSkin;
	}

	@Column(name = "easy_awake")
	public Boolean getEasyAwake() {
		return this.easyAwake;
	}

	public void setEasyAwake(Boolean easyAwake) {
		this.easyAwake = easyAwake;
	}

	@Column(name = "feed_vigour")
	public Boolean getFeedVigour() {
		return this.feedVigour;
	}

	public void setFeedVigour(Boolean feedVigour) {
		this.feedVigour = feedVigour;
	}

	@Column(name = "good_latch")
	public Boolean getGoodLatch() {
		return this.goodLatch;
	}

	public void setGoodLatch(Boolean goodLatch) {
		this.goodLatch = goodLatch;
	}

	@Column(name = "improvements_bf")
	public Boolean getImprovementsBf() {
		return this.improvementsBf;
	}

	public void setImprovementsBf(Boolean improvementsBf) {
		this.improvementsBf = improvementsBf;
	}

	@Column(name = "observed_bf")
	public Boolean getObservedBf() {
		return this.observedBf;
	}

	public void setObservedBf(Boolean observedBf) {
		this.observedBf = observedBf;
	}

	@Column(name = "other_milk_to_child")
	public Boolean getOtherMilkToChild() {
		return this.otherMilkToChild;
	}

	public void setOtherMilkToChild(Boolean otherMilkToChild) {
		this.otherMilkToChild = otherMilkToChild;
	}

	@Column(name = "second_observation")
	public Boolean getSecondObservation() {
		return this.secondObservation;
	}

	public void setSecondObservation(Boolean secondObservation) {
		this.secondObservation = secondObservation;
	}

	@Column(name = "skin_to_skin")
	public Boolean getSkinToSkin() {
		return this.skinToSkin;
	}

	public void setSkinToSkin(Boolean skinToSkin) {
		this.skinToSkin = skinToSkin;
	}

	@Column(name = "warm_to_touch")
	public Boolean getWarmToTouch() {
		return this.warmToTouch;
	}

	public void setWarmToTouch(Boolean warmToTouch) {
		this.warmToTouch = warmToTouch;
	}

	@Column(name = "what_applied")
	public String getWhatApplied() {
		return this.whatApplied;
	}

	public void setWhatApplied(String whatApplied) {
		this.whatApplied = whatApplied;
	}

	@Column(name = "wrapped")
	public Boolean getWrapped() {
		return this.wrapped;
	}

	public void setWrapped(Boolean wrapped) {
		this.wrapped = wrapped;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dpt_booster_date", length = 13)
	public Date getDptBoosterDate() {
		return this.dptBoosterDate;
	}

	public void setDptBoosterDate(Date dptBoosterDate) {
		this.dptBoosterDate = dptBoosterDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "opv_booster_date", length = 13)
	public Date getOpvBoosterDate() {
		return this.opvBoosterDate;
	}

	public void setOpvBoosterDate(Date opvBoosterDate) {
		this.opvBoosterDate = opvBoosterDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_death", length = 13)
	public Date getDateDeath() {
		return this.dateDeath;
	}

	public void setDateDeath(Date dateDeath) {
		this.dateDeath = dateDeath;
	}

	@Column(name = "died")
	public Boolean getDied() {
		return this.died;
	}

	public void setDied(Boolean died) {
		this.died = died;
	}

	@Column(name = "died_village")
	public Boolean getDiedVillage() {
		return this.diedVillage;
	}

	public void setDiedVillage(Boolean diedVillage) {
		this.diedVillage = diedVillage;
	}

	@Column(name = "dupe_reg")
	public Boolean getDupeReg() {
		return this.dupeReg;
	}

	public void setDupeReg(Boolean dupeReg) {
		this.dupeReg = dupeReg;
	}

	@Column(name = "finished_continuum")
	public Boolean getFinishedContinuum() {
		return this.finishedContinuum;
	}

	public void setFinishedContinuum(Boolean finishedContinuum) {
		this.finishedContinuum = finishedContinuum;
	}

	@Column(name = "site_death")
	public String getSiteDeath() {
		return this.siteDeath;
	}

	public void setSiteDeath(String siteDeath) {
		this.siteDeath = siteDeath;
	}

	@Column(name = "refer_child")
	public Boolean getReferChild() {
		return this.referChild;
	}

	public void setReferChild(Boolean referChild) {
		this.referChild = referChild;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "childCase")
	public Set<EbfChildForm> getEbfChildForms() {
		return this.ebfChildForms;
	}

	public void setEbfChildForms(Set<EbfChildForm> ebfChildForms) {
		this.ebfChildForms = ebfChildForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "childCase")
	public Set<PncChildForm> getPncChildForms() {
		return this.pncChildForms;
	}

	public void setPncChildForms(Set<PncChildForm> pncChildForms) {
		this.pncChildForms = pncChildForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "childCase")
	public Set<DeathChildForm> getDeathChildForms() {
		return this.deathChildForms;
	}

	public void setDeathChildForms(Set<DeathChildForm> deathChildForms) {
		this.deathChildForms = deathChildForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "childCase")
	public Set<CloseChildForm> getCloseChildForms() {
		return this.closeChildForms;
	}

	public void setCloseChildForms(Set<CloseChildForm> closeChildForms) {
		this.closeChildForms = closeChildForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "childCase")
	public Set<ReferChildForm> getReferChildForms() {
		return this.referChildForms;
	}

	public void setReferChildForms(Set<ReferChildForm> referChildForms) {
		this.referChildForms = referChildForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "childCase")
	public Set<RegistrationChildForm> getRegistrationChildForms() {
		return this.registrationChildForms;
	}

	public void setRegistrationChildForms(
			Set<RegistrationChildForm> registrationChildForms) {
		this.registrationChildForms = registrationChildForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "childCase")
	public Set<CfChildForm> getCfChildForms() {
		return this.cfChildForms;
	}

	public void setCfChildForms(Set<CfChildForm> cfChildForms) {
		this.cfChildForms = cfChildForms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "childCase")
	public Set<UiChildForm> getUiChildForms() {
		return this.uiChildForms;
	}

	public void setUiChildForms(Set<UiChildForm> uiChildForms) {
		this.uiChildForms = uiChildForms;
	}

}
