package org.motechproject.care.reporting.domain.dimension;

// Generated Jun 3, 2013 2:41:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FlwGroupMap generated by hbm2java
 */
@Entity
@Table(name = "flw_group_map")
public class FlwGroupMap implements java.io.Serializable {

	private int id;
	private FlwGroup flwGroup;
	private Flw flw;

	public FlwGroupMap() {
	}

	public FlwGroupMap(int id) {
		this.id = id;
	}

	public FlwGroupMap(int id, FlwGroup flwGroup, Flw flw) {
		this.id = id;
		this.flwGroup = flwGroup;
		this.flw = flw;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id")
	public FlwGroup getFlwGroup() {
		return this.flwGroup;
	}

	public void setFlwGroup(FlwGroup flwGroup) {
		this.flwGroup = flwGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "flw_id")
	public Flw getFlw() {
		return this.flw;
	}

	public void setFlw(Flw flw) {
		this.flw = flw;
	}

}
