package org.motechproject.care.reporting.domain.dimension;

// Generated Jun 4, 2013 4:50:32 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "location", uniqueConstraints = @UniqueConstraint(columnNames = {
		"district", "block", "panchayat", "village" }))
public class Location implements java.io.Serializable {

	private int id;
	private String district;
	private String block;
	private String panchayat;
	private String village;
	private Set<Flw> flws = new HashSet<Flw>(0);

	public Location() {
	}

	public Location(int id) {
		this.id = id;
	}

	public Location(int id, String district, String block, String panchayat,
			String village, Set<Flw> flws) {
		this.id = id;
		this.district = district;
		this.block = block;
		this.panchayat = panchayat;
		this.village = village;
		this.flws = flws;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "district")
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "block")
	public String getBlock() {
		return this.block;
	}

	public void setBlock(String block) {
		this.block = block;
	}

	@Column(name = "panchayat")
	public String getPanchayat() {
		return this.panchayat;
	}

	public void setPanchayat(String panchayat) {
		this.panchayat = panchayat;
	}

	@Column(name = "village")
	public String getVillage() {
		return this.village;
	}

	public void setVillage(String village) {
		this.village = village;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
	public Set<Flw> getFlws() {
		return this.flws;
	}

	public void setFlws(Set<Flw> flws) {
		this.flws = flws;
	}

}
