package org.motechproject.care.reporting.domain.measure;

// Generated May 16, 2013 2:49:27 PM by Hibernate Tools 3.4.0.CR1

import org.motechproject.care.reporting.domain.dimension.Flw;
import org.motechproject.care.reporting.domain.dimension.MotherCase;

import javax.persistence.*;
import java.util.Date;

/**
 * CfMotherForm generated by hbm2java
 */
@Entity
@Table(name = "cf_mother_form", uniqueConstraints = @UniqueConstraint(columnNames = "form_id"))
public class CfMotherForm implements java.io.Serializable {

	private int id;
	private MotherCase motherCase;
	private Flw flw;
	private String formId;
	private Date timeend;
	private Date timestart;
	private Date dateModified;
	private Date dateCf1;
	private Date dateCf2;
	private Date dateCf3;
	private Date dateCf4;
	private Date dateCf5;
	private Date dateCf6;
	private Date dateLastVisit;
	private Date dateNextCf;
	private String lastVisitType;
	private Short cfVisitNum;
	private Integer children;
	private Short numChildren;
	private Boolean playCompFeedingVid;

	public CfMotherForm() {
	}

	public CfMotherForm(int id) {
		this.id = id;
	}

	public CfMotherForm(int id, MotherCase motherCase, Flw flw, String formId,
			Date timeend, Date timestart, Date dateModified, Date dateCf1,
			Date dateCf2, Date dateCf3, Date dateCf4, Date dateCf5,
			Date dateCf6, Date dateLastVisit, Date dateNextCf,
			String lastVisitType, Short cfVisitNum, Integer children,
			Short numChildren, Boolean playCompFeedingVid) {
		this.id = id;
		this.motherCase = motherCase;
		this.flw = flw;
		this.formId = formId;
		this.timeend = timeend;
		this.timestart = timestart;
		this.dateModified = dateModified;
		this.dateCf1 = dateCf1;
		this.dateCf2 = dateCf2;
		this.dateCf3 = dateCf3;
		this.dateCf4 = dateCf4;
		this.dateCf5 = dateCf5;
		this.dateCf6 = dateCf6;
		this.dateLastVisit = dateLastVisit;
		this.dateNextCf = dateNextCf;
		this.lastVisitType = lastVisitType;
		this.cfVisitNum = cfVisitNum;
		this.children = children;
		this.numChildren = numChildren;
		this.playCompFeedingVid = playCompFeedingVid;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "case_id")
	public MotherCase getMotherCase() {
		return this.motherCase;
	}

	public void setMotherCase(MotherCase motherCase) {
		this.motherCase = motherCase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public Flw getFlw() {
		return this.flw;
	}

	public void setFlw(Flw flw) {
		this.flw = flw;
	}

	@Column(name = "form_id", unique = true, length = 36)
	public String getFormId() {
		return this.formId;
	}

	public void setFormId(String formId) {
		this.formId = formId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timeend", length = 35)
	public Date getTimeend() {
		return this.timeend;
	}

	public void setTimeend(Date timeend) {
		this.timeend = timeend;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestart", length = 35)
	public Date getTimestart() {
		return this.timestart;
	}

	public void setTimestart(Date timestart) {
		this.timestart = timestart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modified", length = 35)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_cf_1", length = 13)
	public Date getDateCf1() {
		return this.dateCf1;
	}

	public void setDateCf1(Date dateCf1) {
		this.dateCf1 = dateCf1;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_cf_2", length = 13)
	public Date getDateCf2() {
		return this.dateCf2;
	}

	public void setDateCf2(Date dateCf2) {
		this.dateCf2 = dateCf2;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_cf_3", length = 13)
	public Date getDateCf3() {
		return this.dateCf3;
	}

	public void setDateCf3(Date dateCf3) {
		this.dateCf3 = dateCf3;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_cf_4", length = 13)
	public Date getDateCf4() {
		return this.dateCf4;
	}

	public void setDateCf4(Date dateCf4) {
		this.dateCf4 = dateCf4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_cf_5", length = 13)
	public Date getDateCf5() {
		return this.dateCf5;
	}

	public void setDateCf5(Date dateCf5) {
		this.dateCf5 = dateCf5;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_cf_6", length = 13)
	public Date getDateCf6() {
		return this.dateCf6;
	}

	public void setDateCf6(Date dateCf6) {
		this.dateCf6 = dateCf6;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_last_visit", length = 13)
	public Date getDateLastVisit() {
		return this.dateLastVisit;
	}

	public void setDateLastVisit(Date dateLastVisit) {
		this.dateLastVisit = dateLastVisit;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_next_cf", length = 13)
	public Date getDateNextCf() {
		return this.dateNextCf;
	}

	public void setDateNextCf(Date dateNextCf) {
		this.dateNextCf = dateNextCf;
	}

	@Column(name = "last_visit_type", length = 20)
	public String getLastVisitType() {
		return this.lastVisitType;
	}

	public void setLastVisitType(String lastVisitType) {
		this.lastVisitType = lastVisitType;
	}

	@Column(name = "cf_visit_num")
	public Short getCfVisitNum() {
		return this.cfVisitNum;
	}

	public void setCfVisitNum(Short cfVisitNum) {
		this.cfVisitNum = cfVisitNum;
	}

	@Column(name = "children")
	public Integer getChildren() {
		return this.children;
	}

	public void setChildren(Integer children) {
		this.children = children;
	}

	@Column(name = "num_children")
	public Short getNumChildren() {
		return this.numChildren;
	}

	public void setNumChildren(Short numChildren) {
		this.numChildren = numChildren;
	}

	@Column(name = "play_comp_feeding_vid")
	public Boolean getPlayCompFeedingVid() {
		return this.playCompFeedingVid;
	}

	public void setPlayCompFeedingVid(Boolean playCompFeedingVid) {
		this.playCompFeedingVid = playCompFeedingVid;
	}

}
