<?xml version='1.0' ?>
<data uiVersion="1" version="1" name="New Beneficiary" xmlns:cc="http://commcarehq.org/xforms" xmlns="http://bihar.commcarehq.org/pregnancy/new">
    <n0:meta xmlns:n0="http://openrosa.org/jr/xforms">
        <n0:deviceID>DOR73YCLJKEISKEMJMVEPAU30</n0:deviceID>
        <n0:timeStart>2012-07-21T13:52:00.773Z</n0:timeStart>
        <n0:timeEnd>2012-07-21T13:54:18.954Z</n0:timeEnd>
        <n0:username>8969821683</n0:username>
        <n0:userID>$userId$</n0:userID>
        <n0:instanceID>$instanceId$</n0:instanceID>
        <cc:appVersion>v2.0.0alpha (990ba3-e6e3c5-unvers-2.1.0-Nokia/S40-native-input) #48 b:2012-Jul-26 r:2012-Jul-28</cc:appVersion>
    </n0:meta>
    <n1:case case_id="$caseId$" date_modified="2012-07-21T13:54:18.954Z" user_id="$userId$" xmlns:n1="http://commcarehq.org/case/transaction/v2">
        <n1:create>
            <n1:case_type>cc_bihar_pregnancy</n1:case_type>
            <n1:owner_id>$ownerId$</n1:owner_id>
            <n1:case_name>&#2352;&#2306;&#2332;&#2344; &#2342;&#2375;&#2357;&#2368;</n1:case_name>
        </n1:create>
        <n1:update>
            <n1:last_visit_type>new</n1:last_visit_type>
            <n1:date_last_visit>2012-07-21</n1:date_last_visit>
            <n1:date_next_reg>2012-07-21</n1:date_next_reg>
            <n1:mother_alive>yes</n1:mother_alive>
            <n1:mother_name>&#2352;&#2306;&#2332;&#2344; &#2342;&#2375;&#2357;&#2368;</n1:mother_name>
            <n1:husband_name>&#2346;&#2381;&#2352;&#2350;&#2379;&#2342; &#2350;&#2369;&#2326;&#2367;&#2351;&#2366;</n1:husband_name>
            <n1:hh_number>14</n1:hh_number>
            <n1:family_number>2</n1:family_number>
            <n1:mother_dob />
        </n1:update>
    </n1:case>
    <full_name>&#2352;&#2306;&#2332;&#2344; &#2342;&#2375;&#2357;&#2368;</full_name>
    <husband_name>&#2346;&#2381;&#2352;&#2350;&#2379;&#2342; &#2350;&#2369;&#2326;&#2367;&#2351;&#2366;</husband_name>
    <hh_number>14</hh_number>
    <family_number>2</family_number>
    <dob_known>no</dob_known>
    <caste>sc_st</caste>
    <success>OK</success>
    <age_calc />
</data>