{
    "meta": {
        "limit": 2,
        "next": null,
        "offset": 0,
        "previous": null,
        "total_count": 410
    },
    "objects": [
        {
            "case_sharing": true,
            "domain": "care-bihar",
            "id": "$groupId1$",
            "metadata": {
                "awc-code": ""
            },
            "name": "Group 1",
            "path": [],
            "reporting": true,
            "resource_uri": "",
            "users": []
        },
        {
            "case_sharing": false,
            "domain": "care-bihar",
            "id": "$groupId2$",
            "metadata": {
                "awc-code": "123"
            },
            "name": "Group 2",
            "path": [],
            "reporting": true,
            "resource_uri": "",
            "users": [
                "$providerId1", "$providerId2"
            ]
        },
        {
            "case_sharing": true,
            "domain": "care-bihar",
            "id": "$groupId3$",
            "metadata": {
                "awc-code": "123"
            },
            "name": "Group 3",
            "path": [],
            "reporting": true,
            "resource_uri": "",
            "users": [
                "$providerId2", "$providerId3"
            ]
        }
    ]
}