{
    "meta": {
        "limit": 2,
        "next": null,
        "offset": 0,
        "previous": null,
        "total_count": 600
    },
    "objects": [
        {
            "default_phone_number": "8294168471",
            "email": "",
            "first_name": "Dr.Pramod",
            "groups": [
                "$groupId2$"
            ],
            "id": "$providerId1$",
            "last_name": "Kumar Gautam",
            "phone_numbers": [
                "8294168471"
            ],
            "resource_uri": "",
            "user_data": {
                "asset-id": "MP818",
                "awc-code": "",
                "block": "Sonbarsa",
                "district": "",
                "imei-no": "351971057712199",
                "location-code": "",
                "panchayat": "",
                "role": "MOIC",
                "subcentre": "",
                "user_type": "",
                "village": ""
            },
            "username": "8294168471@care-bihar.commcarehq.org"
        },
    	{
            "default_phone_number": "8294168762",
            "email": "harry_potter@hogwarts.com",
            "first_name": "Harry",
            "groups": [
                "$groupId2$",
			    "$groupId1$"
            ],
            "id": "$providerId2$",
            "last_name": "Potter",
            "phone_numbers": [
                "8294168762","8294168763","8294168764"
            ],
            "resource_uri": "test",
            "user_data": {
                "asset-id": "MP1069",
                "awc-code": "122",
                "block": "Sattarkatyea",
                "district": "chittoor",
                "imei-no": "352445051471325",
                "location-code": "030",
                "panchayat": "test",
                "role": "BHM",
                "subcentre": "Gryffindor",
                "user_type": "wizard",
                "village": "village",
		        "population":"4356890",
		        "ward":"34",
		        "caste":"caste",
		        "education":"education",
		        "dob":"04/02/2000",
		        "ictcordinator":"ictccoror",
		        "remarks":"awesome job done"
            },
            "username": "8294168762@care-bihar.commcarehq.org"
        }
    ]
}